// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAccountBalanceData, GetAccountBalanceErrors, GetAccountBalanceResponses, GetBalanceSheetData, GetBalanceSheetErrors, GetBalanceSheetResponses, GetIncomeStatementData, GetIncomeStatementErrors, GetIncomeStatementResponses, GetTransactionData, GetTransactionErrors, GetTransactionResponses, GetTrialBalanceData, GetTrialBalanceErrors, GetTrialBalanceResponses, ListAccountsData, ListAccountsErrors, ListAccountsResponses, OpenAccountData, OpenAccountErrors, OpenAccountResponses, PostTransactionData, PostTransactionErrors, PostTransactionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List the accounts on one book.
 *
 * **ADR-0019 refused every listing; ADR-0021 withdraws that for accounts and
 * keeps it for transactions.** ADR-0019's ground was that a listing *"needs
 * an ordering and a page key this spike did not design"* — a *not yet*, not a
 * *never* — and for accounts the ordering already exists: `pk_accounts` is
 * `(tenant_id, id)` and `id` is `uuidv7()`, which is time-ordered and total.
 * A TRANSACTION listing would still have to choose between the recorded and
 * the effective axis, which is the one place a listing can be confidently
 * wrong.
 */
export const listAccounts = <ThrowOnError extends boolean = false>(options: Options<ListAccountsData, ThrowOnError>): RequestResult<ListAccountsResponses, ListAccountsErrors, ThrowOnError> => (options.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({ url: '/v1/accounts', ...options });

/**
 * Open an account.
 *
 * The response set below is this endpoint's real one, not a shared error
 * enum's: the six 422 `type`s named are exactly the ones the writer can
 * produce here. `account_exists` never appears on the posting endpoint and
 * `account_unknown` never appears here, which is precisely why opening
 * carries its own error type in the core (ADR-0021).
 */
export const openAccount = <ThrowOnError extends boolean = false>(options: Options<OpenAccountData, ThrowOnError>): RequestResult<OpenAccountResponses, OpenAccountErrors, ThrowOnError> => (options.client ?? client).post<OpenAccountResponses, OpenAccountErrors, ThrowOnError>({
    url: '/v1/accounts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read one account's posted balance.
 *
 * **No cursor, and that is the contract**: this reads the balance cache,
 * which means POSTED, NOW (ADR-0010). Pinning it to a cursor would be a
 * second definition of a balance, and the journal-based answer is the trial
 * balance next door.
 */
export const getAccountBalance = <ThrowOnError extends boolean = false>(options: Options<GetAccountBalanceData, ThrowOnError>): RequestResult<GetAccountBalanceResponses, GetAccountBalanceErrors, ThrowOnError> => (options.client ?? client).get<GetAccountBalanceResponses, GetAccountBalanceErrors, ThrowOnError>({ url: '/v1/accounts/{account_id}/balance', ...options });

/**
 * Read the balance-sheet face as at one instant.
 */
export const getBalanceSheet = <ThrowOnError extends boolean = false>(options: Options<GetBalanceSheetData, ThrowOnError>): RequestResult<GetBalanceSheetResponses, GetBalanceSheetErrors, ThrowOnError> => (options.client ?? client).get<GetBalanceSheetResponses, GetBalanceSheetErrors, ThrowOnError>({ url: '/v1/reports/balance-sheet', ...options });

/**
 * Read the income statement over a half-open effective range.
 */
export const getIncomeStatement = <ThrowOnError extends boolean = false>(options: Options<GetIncomeStatementData, ThrowOnError>): RequestResult<GetIncomeStatementResponses, GetIncomeStatementErrors, ThrowOnError> => (options.client ?? client).get<GetIncomeStatementResponses, GetIncomeStatementErrors, ThrowOnError>({ url: '/v1/reports/income-statement', ...options });

/**
 * Read the trial balance.
 *
 * **One endpoint serves both of ADR-0006's time axes, by parameter and never
 * by a mode flag**: the RECORDED axis is the cursor — widen the range and
 * vary it — and the EFFECTIVE axis is the range — fix the cursor and vary
 * it. Two resources for two parameters of one function is Formance's
 * `pit`-resolves-to-six-columns mistake (ADR-0019 C2).
 */
export const getTrialBalance = <ThrowOnError extends boolean = false>(options: Options<GetTrialBalanceData, ThrowOnError>): RequestResult<GetTrialBalanceResponses, GetTrialBalanceErrors, ThrowOnError> => (options.client ?? client).get<GetTrialBalanceResponses, GetTrialBalanceErrors, ThrowOnError>({ url: '/v1/reports/trial-balance', ...options });

/**
 * Post a transaction.
 *
 * The response set below is this endpoint's real one, not a shared error
 * enum's: the eight 422 `type`s named are exactly the ones the writer can
 * produce here, and nothing else is documented (spike 021 found both
 * candidate libraries fanning shared enums across statuses their endpoints
 * cannot return — the fix is to declare per endpoint, so this project
 * does).
 */
export const postTransaction = <ThrowOnError extends boolean = false>(options: Options<PostTransactionData, ThrowOnError>): RequestResult<PostTransactionResponses, PostTransactionErrors, ThrowOnError> => (options.client ?? client).post<PostTransactionResponses, PostTransactionErrors, ThrowOnError>({
    url: '/v1/transactions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read a transaction back.
 *
 * No cursor and no chart version: a transaction and its entries are
 * immutable (`ck_txn__append_only` and `ck_entries__append_only`, both
 * `ENABLE ALWAYS`), so there is nothing for an as-of to pin (ADR-0019).
 */
export const getTransaction = <ThrowOnError extends boolean = false>(options: Options<GetTransactionData, ThrowOnError>): RequestResult<GetTransactionResponses, GetTransactionErrors, ThrowOnError> => (options.client ?? client).get<GetTransactionResponses, GetTransactionErrors, ThrowOnError>({ url: '/v1/transactions/{transaction_id}', ...options });
