// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * One account's posted balance.
 */
export type AccountBalanceRead = {
    account_id: string;
    /**
     * Always `now`. This endpoint reads the balance CACHE, which means
     * POSTED (ADR-0010), and pinning it to a cursor would be a second
     * definition of a balance — so the field is a statement of what the
     * number means rather than a parameter's echo.
     */
    as_of: string;
    currency: string;
    /**
     * Minor units, debit-positive, as an exact-integer decimal string. A
     * credit-normal account reads negative here and the presentation flip is
     * the reader's (ADR-0010).
     */
    posted_minor: string;
};

/**
 * The body of `POST /v1/accounts`.
 *
 * **What is NOT here is the design** (ADR-0021): there is no `category`, no
 * `normal_balance` and no `counterparty_scope`. `ledger_accounts` carries all
 * three as COPIES of the chart row, held honest by `fk_accounts__type` and
 * `fk_accounts__scope` — so a body that stated them could disagree with the
 * chart, and the caller would be handed a foreign-key error rather than an
 * answer. The caller names a `purpose` and the server reads the rest, which
 * makes a whole class of refusals unreachable rather than merely reported.
 */
export type AccountBody = {
    /**
     * ISO 4217 alphabetic code, three uppercase ASCII letters. One account
     * holds one currency.
     */
    currency: string;
    /**
     * Caller-supplied replay key, unique per tenant — and in the SAME
     * namespace a posting's key lives in, because it is the same spine
     * (`ledger_events`, ADR-0005). Sending the same key with the same body
     * replays the stored result; with a different body it is refused as
     * `idempotency_key_reused` (ADR-0013 §2), and that includes a key an
     * earlier POSTING claimed.
     */
    idempotency_key: string;
    /**
     * Caller's own JSON object, stored as given. It must BE an object:
     * `jsonb` would store a bare number as happily, and a metadata field
     * that is sometimes a scalar is a shape every reader has to defend
     * against. A scalar, an array or a string here is
     * `422 invalid_request` — the writer checks it (`AccountOpening::new`),
     * so the `object` below is a claim the service actually keeps rather
     * than a hope the schema expresses.
     *
     * Typed as an object because the alternative is worse than vague:
     * `serde_json::Value` with no annotation generates as `unknown`, and a
     * caller holding an `unknown` can only `JSON.stringify` the one field
     * this API exists to let them put their own structure in.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Who owns it. Required for every `owner_type` except `house`, and
     * refused for `house` — `ck_accounts__house_has_no_owner`, answered as
     * `account_owner_mismatched`.
     */
    owner_id?: string | null;
    owner_type: OwnerTypeBody;
    /**
     * The account type, by its chart code — `customer_receivable`,
     * `fee_revenue`, and whatever else this deployment's chart carries. A
     * code `account_types` does not hold is `account_type_unknown`.
     */
    purpose: string;
    /**
     * How many stripes the writer spreads this account's balance row across,
     * 1–1024. Omitted means one. **A hint, not an invariant** (ADR-0013 §4):
     * a reader sums the stripe rows that exist, never the range `0..n-1`, so
     * nothing is stranded by getting it wrong — but no stripe ever appears
     * in a response, so this is the only place the number is spoken.
     */
    stripe_count?: number | null;
    /**
     * The book this account belongs to. Named in the body by decision
     * (ADR-0017): data scoping, never an identity claim.
     */
    tenant_id: string;
};

/**
 * The stored result of an accepted opening: the event, and the account it
 * caused — **the whole account**, not its id.
 *
 * **Two UUIDs undercut ADR-0021's own design.** The decision's centre is
 * that the caller names a `purpose` and the server DERIVES `category`,
 * `normal_balance` and `counterparty_scope`; answering with an id meant the
 * derived triple could only be seen by a second call to `GET /v1/accounts`
 * plus a client-side scan, because there is no `GET /v1/accounts/{id}` and
 * the listing filters on `purpose` and `owner_id` but not on the account.
 * "Show me the account I just opened" was a paged search. It is one field
 * now, and it is the SAME [`AccountRead`] a listing row is — one type, so
 * the two cannot come to disagree about what an account looks like.
 *
 * `event_id` stays beside it: opening an account writes an EVENT and no
 * ledger transaction, which is the case ADR-0005 justified the event log by,
 * and the spine is a fact a caller should still be able to see.
 */
export type AccountCreated = {
    /**
     * The account, as the register holds it. Never null, unlike a posting's
     * `transaction_id`: an accepted opening always wrote one, and a replay
     * finds it by the natural key its own body names.
     */
    account: AccountRead;
    /**
     * The event row this call claimed — or, on a replay, the one it found.
     */
    event_id: string;
};

/**
 * One page of the account register.
 */
export type AccountListRead = {
    /**
     * The page, in creation order — `id` is `uuidv7()`, so ordering by it
     * orders by when each account was opened.
     *
     * **An empty list is a legitimate answer** and never a 404: it is what
     * an unknown tenant, a typo'd tenant, a tenant with no accounts and a
     * reader scoped elsewhere all produce, and two of those are the
     * fail-closed path working correctly (ADR-0019).
     */
    accounts: Array<AccountRead>;
    /**
     * The `after` to send for the next page, or `null` when this page did
     * not fill. **A full page means "there may be more", never "there is"**:
     * the alternative is reading one row past every page to be certain, and
     * a caller that follows this key to an empty page has learnt the same
     * thing one request later.
     */
    next_after: string | null;
};

/**
 * One account, as the register holds it — the representation BOTH of this
 * resource's verbs answer with: a row of the listing, and the whole of an
 * accepted opening's `account`.
 *
 * **No balance, and that is contract** (ADR-0021): balances are per currency
 * and per stripe, so a balance per row would be N+1, and
 * `GET /v1/accounts/{account_id}/balance` answers that question one account
 * at a time and exactly. `metadata` is here and a balance is not, and the
 * two are different questions: metadata is the caller's own object, written
 * at the opening and readable on no other route.
 */
export type AccountRead = {
    account_id: string;
    /**
     * `asset`, `liability`, `equity`, `revenue` or `expense` — the chart's,
     * copied onto the account and held honest by `fk_accounts__type`.
     */
    category: string;
    /**
     * `none`, `shared` or `per_shard` — whether this type's positions may be
     * summed for reporting, and the reason a `per_shard` type cannot live in
     * a house account (ADR-0012).
     */
    counterparty_scope: string;
    /**
     * When the account was opened — the database's clock.
     */
    created_at: string;
    currency: string;
    /**
     * The caller's own object, as the opening set it — `{}` when it named
     * none, because the column is `NOT NULL DEFAULT '{}'`.
     *
     * It is here because until now a caller could WRITE metadata and had no
     * route that read it back, which is a hole rather than a missing
     * feature. ADR-0021's "identity plus `stripe_count`" is extended by this
     * one field and by nothing else: the part of that sentence that was
     * load-bearing is the absence of BALANCES, and they are still absent.
     *
     * Always an object, never a scalar and never null: the column is
     * `NOT NULL DEFAULT '{}'` and the writer refuses a body whose metadata
     * is not an object, so both ends of the round trip hold the shape the
     * schema declares.
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * `debit` or `credit`. **Not derivable from `category`**: a loss
     * allowance is an asset with a credit normal balance, which is why the
     * schema stores both.
     */
    normal_balance: string;
    /**
     * `null` on a house account, which is the ledger's own side and has no
     * owner.
     */
    owner_id: string | null;
    /**
     * `company`, `platform`, `bank_account` or `house`.
     */
    owner_type: string;
    /**
     * The account type, by its chart code.
     */
    purpose: string;
    /**
     * How many stripes the writer spreads this account's balance row across.
     * **The one place a stripe count is spoken** — no stripe VALUE appears
     * in any response (ADR-0013 §4), and this is the hint, not a position.
     */
    stripe_count: number;
};

/**
 * One page of one account's entries: the axis they were ordered by, the
 * cursor they were pinned at, and the key of the next page.
 */
export type AccountStatementRead = {
    /**
     * The axis this page was ordered by, echoed — `recorded` or `effective`.
     */
    axis: string;
    /**
     * The page, in the axis's order. **An empty list is a legitimate answer**
     * for an account with no entries at this cursor, in this range; an
     * account that does not exist is a 404 instead, which is a distinction
     * only the account register can draw (ADR-0019).
     */
    entries: Array<StatementEntryRead>;
    /**
     * The `after` to send for the next page, or `null` when this page did not
     * fill. **A full page means "there may be more", never "there is"** — the
     * same rule `GET /v1/accounts` follows, and for the same reason: the
     * alternative is reading one row past every page to be certain.
     */
    next_after: string | null;
    /**
     * The commit position this page ran at — supplied or server-pinned.
     * Store it and send it back to walk the rest of this same book: the page
     * after it is then the page after it *was*, whatever has committed since.
     */
    pinned_cursor: string;
};

/**
 * The body of `POST /v1/periods/{code}/close`.
 *
 * **There is no `idempotency_key` field, and its absence is the design**
 * (ADR-0011 §2): the key is `tenant:close:period:currency`, derived by the
 * writer, so `uq_events__idempotency` refuses a second attempt on its own
 * rather than by a check anyone had to remember to write. A caller has
 * nothing to vary here — a close is per `(tenant, period, currency)` because
 * `pk_closes` is.
 */
export type ClosePeriodBody = {
    /**
     * ISO 4217 alphabetic code, three uppercase ASCII letters. One call
     * closes one currency.
     */
    currency: string;
    /**
     * The book being closed. Named in the body by decision (ADR-0017): data
     * scoping, never an identity claim.
     */
    tenant_id: string;
};

/**
 * The commit horizon, on its own.
 */
export type CursorRead = {
    /**
     * The current horizon, as a decimal string — an `xid8` is a 64-bit
     * unsigned value and JSON numbers are not. Send it back as `cursor` on
     * any report route to pin that report here; everything strictly below it
     * has finished committing and can never grow.
     */
    cursor: string;
};

/**
 * One leg. `amount_minor` is an exact-integer decimal STRING, the same shape
 * the request sends and every report total already carried: a `bigint`
 * reaches far past 2⁵³ and a JSON number does not carry it exactly, so the
 * read-back of a large posting was silently one lower than what was written
 * (ADR-0019's asymmetry, corrected by building a client against it).
 */
export type EntryRead = {
    account_id: string;
    /**
     * The account's own gapless sequence number for this leg. The counter is
     * per `(account, stripe)` — documented, never exposed: no stripe appears
     * in any response (ADR-0013 §4).
     */
    account_seq: number;
    /**
     * Minor units, as an exact-integer decimal string — **not a JSON
     * number** (ADR-0022). `ledger_entries.amount_minor` is a `bigint` and
     * JSON has no integer type, so a large amount read as a number comes back
     * silently wrong. Always digits and always strictly positive here: the
     * sign a caller may send is the domain's refusal, never a stored value.
     */
    amount_minor: string;
    currency: string;
    /**
     * `debit` or `credit`. Direction carries the sign; the amount never does.
     */
    direction: string;
};

/**
 * The error body: a stable machine-readable `type`, prose in `detail`.
 */
export type ErrorBody = {
    /**
     * Human-readable explanation. Not stable; do not parse.
     */
    detail: string;
    /**
     * Stable machine-readable identifier. Parse this, never `detail`.
     */
    type: string;
};

/**
 * Who an account belongs to — the schema's `account_owner_type`. `house` is
 * the ledger's own side of a movement and is the one value that carries NO
 * `owner_id`; the other three name one.
 */
export type OwnerTypeBody = 'company' | 'platform' | 'bank_account' | 'house';

/**
 * The body of `POST /v1/periods`.
 *
 * **`starts_at` and `ends_at` are RESOLVED INSTANTS and `tz` is provenance,
 * and that split is the whole design** (ADR-0011 §5, ADR-0024). The API never
 * accepts a local date and a zone and resolves them itself, because that is
 * measured to be wrong twice over: a local midnight is not always a real
 * instant — `2018-11-04 00:00` in `America/Sao_Paulo` never happened, and
 * PostgreSQL silently resolves it to 01:00 — and the same local date resolves
 * an hour apart across a tzdata update. The caller resolves once, sends the
 * instants, and names the zone so a reader can say *"February in
 * America/New_York"*.
 */
export type PeriodBody = {
    /**
     * The period's label — `2026-08`, `FY2026Q1`. **A label, not a key of
     * time**: nothing parses it, and the instants below are what every report
     * filters on. It is unique per tenant (`pk_periods`) and it is the
     * `{code}` the close route names.
     */
    code: string;
    /**
     * The first instant NOT in the period, RFC 3339 — the range is
     * **half-open**, `[starts_at, ends_at)`. A close's own transaction is
     * dated one microsecond below this, which `timestamptz`'s microsecond
     * resolution makes exact rather than a `23:59:59` approximation.
     */
    ends_at: string;
    /**
     * Caller-supplied replay key, unique per tenant — and in the SAME
     * namespace a posting's and an opening's key live in, because it is the
     * same spine (`ledger_events`, ADR-0005). Sending the same key with the
     * same body replays the stored result; with a different body it is
     * refused as `idempotency_key_reused` (ADR-0013 §2).
     */
    idempotency_key: string;
    /**
     * The first instant IN the period, RFC 3339.
     */
    starts_at: string;
    /**
     * The book this period belongs to. Named in the body by decision
     * (ADR-0017): data scoping, never an identity claim.
     */
    tenant_id: string;
    /**
     * The IANA zone whose business date this period is — `UTC`,
     * `America/New_York`. **Provenance, never the boundary**: it is recorded
     * and never re-resolved, and a name the server's tzdata does not carry is
     * `period_zone_unknown`.
     */
    tz: string;
};

/**
 * What a close wrote.
 *
 * **No `replayed` flag, and its absence is the contract** (ADR-0011 §2): the
 * idempotency key is derived, so a second close of one period and currency is
 * `period_already_closed` and there is no stored result to re-render.
 */
export type PeriodClosedRead = {
    /**
     * How many rows the checkpoint wrote — one per account with a posted
     * entry in this currency effective before the period end, not only the
     * swept ones. The checkpoint is the whole effective-axis position at the
     * boundary, which is what `balance_sheet_at` reads.
     */
    checkpoint_rows: number;
    /**
     * The commit cursor the checkpoint was computed at, as a decimal STRING —
     * an `xid8` is 64-bit, and every cursor on this surface travels as a
     * string for the reason every amount does (ADR-0022).
     *
     * It is the value `ledger_period_closes.computed_at_xid` carries, and
     * everything below it had committed: an entry backdated into this period
     * afterwards arrives ABOVE it, so it is a tail term rather than an
     * invalidation, and `close_disclosures` is where such arrivals are
     * enumerated.
     */
    computed_at_xid: string;
    currency: string;
    /**
     * The closing transaction's own date: `ends_at - 1 microsecond`, the last
     * *representable* instant inside a half-open period.
     */
    effective_at: string;
    /**
     * The event row that claimed the derived key.
     */
    event_id: string;
    period_code: string;
    /**
     * One entry per temporary account the close moved, in account order.
     * **Empty is a legitimate close**, not a refusal: a period with no
     * revenue or expense movement has nothing to sweep, and migration
     * `00004` carved that case out of `recon_transaction_breaks` precisely so
     * a quiet month is not an error (ADR-0020).
     */
    swept: Array<SweptRead>;
    /**
     * The closing transaction — an ordinary balanced transaction, posted
     * through the same primitive as any other (ADR-0011 §2). It is readable
     * on `GET /v1/transactions/{transaction_id}` like any other, and it
     * cannot be reversed (ADR-0016).
     */
    transaction_id: string;
};

/**
 * The stored result of an accepted definition: the event, and the period it
 * caused.
 *
 * `event_id` is here for the reason it is on an opening's answer: defining a
 * period writes an EVENT and no ledger transaction, which is the case
 * ADR-0005 justified the event log by, and the spine is a fact a caller
 * should be able to see.
 */
export type PeriodCreated = {
    /**
     * The event row this call claimed — or, on a replay, the one it found.
     */
    event_id: string;
    period: PeriodRead;
};

/**
 * One period as `ledger_periods` holds it, on the wire — read back from the
 * insert, never re-rendered from the request, for the reason an account's
 * answer is read back from the register: the instants the ROW carries are the
 * ones every report will filter on.
 */
export type PeriodRead = {
    code: string;
    ends_at: string;
    starts_at: string;
    /**
     * The zone as provenance, exactly as it was sent.
     */
    tz: string;
};

/**
 * One movement of money: `amount_minor` leaves `source` and arrives at
 * `destination`. Direction is carried by the pair, never by a sign.
 */
export type PostingBody = {
    /**
     * Minor units of `currency`, strictly positive, as an exact-integer
     * decimal STRING — never a JSON number.
     *
     * **The column is exact and the wire was not.** `ledger_entries.amount_minor`
     * is a `bigint`, which reaches far past 2⁵³, and JSON has no integer type
     * at all: RFC 8259 leaves precision beyond an IEEE-754 double to the
     * implementation, and JavaScript's parser is one that loses it.
     * Demonstrated against this API rather than reasoned — a posting of
     * 9007199254740993 was accepted and `JSON.parse` read it back as
     * 9007199254740992, silently off by one in both directions. So a single
     * amount travels the way every report total already does.
     *
     * **The accepted form is three rules, and the schema can express one of
     * them.** They are stated here in full because a client that has to
     * guess ends up restating them from the refusal messages, with nothing
     * comparing its copy against this one:
     *
     * 1. **The grammar `^-?[0-9]+$`** — digits, optionally preceded by a
     * single `-`. No leading `+`, no surrounding whitespace, no decimal
     * point, no exponent, no thousands separator, and not the empty
     * string. Each is refused rather than trimmed or coerced, because
     * two spellings of one amount hash differently under the idempotency
     * key that covers the request bytes. **This rule is the `pattern`
     * above** — a client generated from this document can check it
     * without reading this sentence.
     * 2. **It must fit a signed 64-bit integer**, which is
     * `ledger_entries.amount_minor`'s own range: −9223372036854775808 to
     * 9223372036854775807 inclusive. **JSON Schema cannot express this**
     * — `minimum`/`maximum` bound a number and this is a string, and no
     * pattern distinguishes 19 digits that fit from 19 that do not. It is
     * enforced by the service, and a value outside it is
     * `422 invalid_request` naming the field.
     * 3. **It must be strictly positive**, so `"0"` and every negative are
     * refused. Direction is carried by the `source`/`destination` pair
     * and never by a sign, which is why the grammar admits a `-` that the
     * domain then refuses: *"not a number"* and *"not positive"* are
     * different things for a caller to fix, and they are answered
     * separately. **Also inexpressible here**, and also
     * `422 invalid_request`.
     *
     * So: rule 1 is checked by this schema; rules 2 and 3 are checked only
     * by the server, and a client that wants to refuse before the round trip
     * has to implement them itself, knowing that this paragraph — not a
     * keyword — is what it is copying.
     */
    amount_minor: string;
    /**
     * ISO 4217 alphabetic code, three uppercase ASCII letters.
     */
    currency: string;
    /**
     * Account the amount arrives at.
     */
    destination: string;
    /**
     * Account the amount leaves.
     */
    source: string;
};

/**
 * One entry of an account's statement — **the leg that touched THIS
 * account**, never the transaction's other legs, which belong to other
 * accounts. `transaction_id` is on every row and
 * `GET /v1/transactions/{transaction_id}` answers the rest (ADR-0023).
 */
export type StatementEntryRead = {
    /**
     * The account's own gapless sequence number for this leg. The counter is
     * per `(account, stripe)` — documented, never exposed: no stripe appears
     * in any response (ADR-0013 §4). It is what a drift check walks, and it
     * is **not** the page key (see `after`).
     */
    account_seq: number;
    /**
     * Minor units, as an exact-integer decimal string — **not a JSON
     * number** (ADR-0022). `ledger_entries.amount_minor` is a `bigint` and
     * JSON has no integer type, so a large amount read as a number comes back
     * silently wrong.
     */
    amount_minor: string;
    currency: string;
    /**
     * `debit` or `credit`. Direction carries the sign; the amount never does.
     */
    direction: string;
    /**
     * When the entry is DATED — the business date, and the effective axis's
     * position.
     */
    effective_at: string;
    /**
     * The entry's own id — `pk_entries`'s column, and the tie-break that
     * makes each axis a TOTAL order.
     */
    entry_id: string;
    /**
     * When the entry was WRITTEN — the database's clock. It is provenance
     * rather than an ordering: the recorded axis is ordered by commit
     * position (`xact_id`), which `recorded_at` cannot stand in for, because
     * a clock reading taken before a commit does not order commits
     * (ADR-0006).
     */
    recorded_at: string;
    /**
     * `pending` or `posted` — the status of the transaction this leg belongs
     * to, and **the field that says whether the balance counts this row**.
     *
     * **A statement is not posted-only.** A pending hold writes entries and
     * draws `account_seq` for them exactly as a posted charge does
     * (ADR-0016), and this page filters no status — so a pending leg has
     * always been here. What it had no way to say was that
     * `GET /v1/accounts/{account_id}/balance` does not count it: that route
     * reads the balance CACHE, which means POSTED (ADR-0010). A row the
     * total excludes now says so on the row, rather than requiring one
     * `GET /v1/transactions/{transaction_id}` per distinct transaction to
     * find out.
     *
     * It never mutates: a pending transaction becomes posted by a NEW
     * transaction naming it in `resolves_id`, which writes its OWN entries —
     * so a settled hold shows on this page as two rows, the pending original
     * and the posted resolution, and not as one row that changed its mind.
     */
    status: string;
    /**
     * The transaction this leg belongs to.
     */
    transaction_id: string;
};

/**
 * One line of a statement face.
 */
export type StatementLineRead = {
    /**
     * Minor units, as an exact-integer decimal string — **not a JSON
     * number**. A report total is an aggregate and can exceed what a JSON
     * number carries exactly, which would be rounded silently by the parser
     * at the other end (ADR-0019). It costs every caller one parse,
     * deliberately.
     */
    amount_minor: string;
    caption: string;
    currency: string;
    /**
     * The chart's line code.
     */
    fs_line: string;
    /**
     * Which side of the face this line belongs to.
     */
    side: string;
    /**
     * The chart's ordering, not a row number.
     */
    sort_order: number;
};

/**
 * A statement face — the same shape for the balance sheet and the income
 * statement, because the two functions return the same columns.
 */
export type StatementRead = {
    /**
     * The chart version this face was presented at — always named, never
     * defaulted. **The residual, stated** (ADR-0019 B6): naming a version
     * pins the presentation only BELOW `max(version)`, because
     * `refuse_stale_chart_version()` freezes history and not the present.
     */
    chart_version: number;
    /**
     * The face, in the chart's own `sort_order`.
     *
     * **What is reproducible at a stored cursor, and what is not**
     * (ADR-0019 B7): the AMOUNTS are; the ROW SET is not. The lines are
     * enumerated from tables that carry no `xact_id` — one new account with
     * nothing posted to it added ten balance-sheet rows at a fixed cursor,
     * every pre-existing amount byte-identical. And an income statement's
     * amounts carry one carve-out of their own: a period close inserted
     * AFTER a statement is issued retroactively removes that transaction's
     * entries from it, because `ledger_period_closes` has no commit position.
     */
    lines: Array<StatementLineRead>;
    pinned_cursor: string;
};

/**
 * Whether the transaction lands on the books or records money that MAY
 * move. Status never mutates: a pending transaction becomes posted by a NEW
 * transaction naming it in `resolves_id`, never by an update (ADR-0016).
 */
export type StatusBody = 'pending' | 'posted';

/**
 * One temporary account the close swept, and how much it moved.
 */
export type SweptRead = {
    account_id: string;
    /**
     * The DEBIT-POSITIVE position moved into `retained_earnings`, as an
     * exact-integer decimal STRING (ADR-0022): a revenue account reads
     * negative and an expense account positive, which is this schema's one
     * sign convention (ADR-0007 §15) and the same one a trial balance's
     * `balance_debit_positive` publishes.
     *
     * A string and not a number because JSON has no integer type and a
     * `bigint` position reaches past 2^53, where a consumer's parser rounds
     * silently.
     */
    position_minor: string;
};

/**
 * The body of `POST /v1/transactions`.
 */
export type TransactionBody = {
    /**
     * When the movement is deemed to have happened, RFC 3339. Required —
     * the writer will not invent a date — EXCEPT on a reversal, where
     * omission means "the target's own effective_at" (ADR-0016's soft
     * convention). A supplied date is taken as given, including one below
     * the target's; the cost of that window is recorded in ADR-0016.
     */
    effective_at?: string | null;
    /**
     * Caller-supplied replay key, unique per tenant. Sending the same key
     * with the same body replays the stored result; with a different body it
     * is refused as `idempotency_key_reused` (ADR-0013 §2).
     */
    idempotency_key: string;
    /**
     * At least one posting — except on a reversal, which must carry NONE:
     * the server derives the mirror from the target.
     */
    postings?: Array<PostingBody>;
    /**
     * The PENDING transaction this one resolves — pending → posted is this
     * new, posted transaction, never an update to the original (ADR-0016).
     * The resolution's postings need not mirror the pending amounts (a
     * partial capture resolves with less); a resolving transaction cannot
     * itself be pending.
     */
    resolves_id?: string | null;
    /**
     * The transaction this one reverses — operational undo, as a NEW
     * posted transaction (ADR-0016): a posted target is mirrored in full
     * (same legs, directions flipped, derived by the server — send NO
     * postings), and a pending target is voided by a zero-posting marker.
     * The target must be an ordinary posting on this tenant's book,
     * itself neither a resolution nor a reversal, and not already
     * superseded.
     */
    reverses_id?: string | null;
    status?: null | StatusBody;
    /**
     * The book this transaction belongs to. Named in the body by decision
     * (ADR-0017): data scoping, never an identity claim — the trust story is
     * the deployment perimeter's, and authenticating callers is the
     * deployer's layer.
     */
    tenant_id: string;
};

/**
 * The stored result of an accepted operation: the event, and the transaction
 * it caused.
 */
export type TransactionCreated = {
    /**
     * The event row this call claimed — or, on a replay, the one it found.
     */
    event_id: string;
    /**
     * The transaction the event caused. Nullable by contract: most accepted
     * operations write no transaction at all (ADR-0013 §2). This endpoint
     * always writes one, but a replay re-renders whatever was stored.
     */
    transaction_id: string | null;
};

/**
 * A transaction as the book holds it, with its entries.
 */
export type TransactionRead = {
    /**
     * When the movement is deemed to have happened — the caller's clock.
     */
    effective_at: string;
    /**
     * The legs. **Empty is a real answer**: a reversal of a pending
     * transaction is a zero-posting void marker (ADR-0016).
     */
    entries: Array<EntryRead>;
    /**
     * The event that caused this transaction.
     */
    event_id: string;
    /**
     * `posting` for an ordinary transaction, `period_close` for a close.
     */
    kind: string;
    /**
     * When the row was written — the database's clock. The two axes are
     * different questions (ADR-0006) and neither is derivable from the other.
     */
    recorded_at: string;
    /**
     * The pending transaction this one resolved, if it is a resolution.
     */
    resolves_id: string | null;
    /**
     * The transaction this one reversed, if it is a reversal.
     */
    reverses_id: string | null;
    /**
     * `pending` or `posted`. **It never mutates**: a pending transaction
     * becomes posted by a NEW transaction naming it in `resolves_id`
     * (ADR-0016), so a `pending` here is what was recorded and not a stage
     * this row is passing through.
     */
    status: string;
    transaction_id: string;
};

/**
 * The trial balance, and the cursor it was pinned at.
 */
export type TrialBalanceRead = {
    /**
     * The commit position this report ran at — supplied or server-pinned.
     * Store it to re-run this exact report; a decimal string, because an
     * `xid8` is a 64-bit unsigned value and JSON numbers are not.
     */
    pinned_cursor: string;
    /**
     * One row per `(account, currency)` with any activity in the window.
     * **An empty list is a legitimate answer** and never a 404: it is what
     * an unknown tenant, a typo'd tenant, a tenant with no accounts, a
     * reader scoped elsewhere and an unscoped session all produce, and two
     * of those five are the fail-closed path working correctly (ADR-0019).
     */
    rows: Array<TrialBalanceRowRead>;
};

/**
 * One `(account, currency)` of the trial balance. Every amount is a decimal
 * string.
 */
export type TrialBalanceRowRead = {
    account_id: string;
    /**
     * The ARITHMETIC value — roll up with this one. `normal_balance` never
     * enters it, so a contra account carries its own sign instead of being
     * flipped twice.
     */
    balance_debit_positive: string;
    /**
     * `asset`, `liability`, `equity`, `revenue` or `expense`.
     */
    category: string;
    /**
     * Gross credits in the window.
     */
    credits: string;
    currency: string;
    /**
     * Gross debits in the window.
     */
    debits: string;
    /**
     * The account type — the chart's code, e.g. `operating_cash`.
     */
    purpose: string;
};

export type ListAccountsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
        /**
         * How many accounts at most, 1–1000. Omitted means 100. A value outside
         * the window is REFUSED rather than clamped: a clamped page is an answer
         * to a question the caller did not ask, and nothing on the wire would
         * say so.
         */
        limit?: number;
        /**
         * The last `account_id` of the previous page — send back the
         * `next_after` an earlier page answered with. Keyset, never an offset
         * (ADR-0021): an offset shifts under concurrent inserts, so a caller
         * paging a growing book silently skips rows.
         */
        after?: string;
        /**
         * Equality on the chart code. **Equality, not search**: no pattern
         * matching and no free text.
         */
        purpose?: string;
        /**
         * Equality on the owner. It selects no house accounts, which have no
         * owner at all.
         */
        owner_id?: string;
    };
    url: '/v1/accounts';
};

export type ListAccountsErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including an `after` that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (a `limit` outside 1–1000, zero or negative included — refused rather than clamped) or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
    /**
     * One page of the account register, in creation order — identity, the derived chart triple, the stripe count and the caller's own `metadata`, and no balances (ADR-0021). An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019).
     */
    200: AccountListRead;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type OpenAccountData = {
    body: AccountBody;
    path?: never;
    query?: never;
    url: '/v1/accounts';
};

export type OpenAccountErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written. Every `type` below is a constraint the schema already holds, refused by name rather than surfaced as a database error (ADR-0021). `type` is one of: `invalid_request` (a precondition on the body failed — a `stripe_count` outside 1–1024, a currency that is not three uppercase letters, a blank tenant, metadata that is not an object — or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key, or resend the original request unchanged; the key namespace is shared with `POST /v1/transactions`, deliberately, because it is the same spine), `account_type_unknown` (`purpose` names no row in this deployment's chart), `account_exists` (`uq_accounts__owned` or `uq_accounts__house` already holds this account; the refusal does not say whose, because within one tenant a collision is always the caller's own), `account_owner_mismatched` (`ck_accounts__house_has_no_owner` — a house account has no owner and an owned account must have one), `account_type_requires_an_owner` (`ck_accounts__per_shard_is_owned` — a type whose split key IS the counterparty cannot be held in a house account, because such an account nets every counterparty at write time and no report can recover it).
     */
    422: ErrorBody;
    /**
     * The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type OpenAccountError = OpenAccountErrors[keyof OpenAccountErrors];

export type OpenAccountResponses = {
    /**
     * Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2). It carries the same full account the 201 did, read back from the register.
     */
    200: AccountCreated;
    /**
     * Opened: this call claimed the idempotency key and wrote the account and its event atomically. The answer carries the whole account, including the `category`, `normal_balance` and `counterparty_scope` the server DERIVED from `purpose` — the same representation `GET /v1/accounts` answers per row (ADR-0021).
     */
    201: AccountCreated;
};

export type OpenAccountResponse = OpenAccountResponses[keyof OpenAccountResponses];

export type GetAccountBalanceData = {
    body?: never;
    path: {
        /**
         * The account to read.
         */
        account_id: string;
    };
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
        /**
         * ISO 4217 alphabetic code.
         */
        currency: string;
    };
    url: '/v1/accounts/{account_id}/balance';
};

export type GetAccountBalanceErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including an `account_id` path segment that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * No such account on this book, or the account does not hold that currency. `type` is `account_unknown` — note that the write path returns 422 under this same `type`, deliberately: there the caller must change the request, here the resource does not exist.
     */
    404: ErrorBody;
    /**
     * Refused. `type` is `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetAccountBalanceError = GetAccountBalanceErrors[keyof GetAccountBalanceErrors];

export type GetAccountBalanceResponses = {
    /**
     * The posted balance, summed over the account's balance rows. An account that exists and has never been written answers `"0"` — which is why this endpoint reads the account register and not only the balance cache (ADR-0019).
     */
    200: AccountBalanceRead;
};

export type GetAccountBalanceResponse = GetAccountBalanceResponses[keyof GetAccountBalanceResponses];

export type GetAccountStatementData = {
    body?: never;
    path: {
        /**
         * The account whose entries to read.
         */
        account_id: string;
    };
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
        /**
         * The two axes `GET /v1/accounts/{account_id}/entries` orders by, as a TYPE
         * — so the generated client's parameter is `"recorded" | "effective"` and a
         * misspelling is a compile error rather than a `422` in production.
         *
         * **It documents the parameter; it does not enforce it.** The handler still
         * takes the axis as text and [`ledger::StatementAxis::parse`] still refuses
         * anything that is not one of these two, by name and with both values in the
         * message (ADR-0023). That refusal is the contract; this enum is the
         * description of it, and a spec that describes a rule is not a spec that
         * keeps it — which is exactly the drift class ADR-0014's cost list names.
         * Deserializing INTO this enum instead would have moved the refusal into
         * axum's extractor and answered `400` where the ledger answers `422` naming
         * both axes, so the parse stays where it is.
         */
        axis: 'recorded' | 'effective';
        /**
         * The commit position to pin the page to — a `pinned_cursor` from an
         * earlier read. Omit it and one is pinned server-side and returned. It
         * bounds BOTH axes: an entry is on this page only if it had committed by
         * this cursor, whatever it is dated.
         */
        cursor?: string;
        /**
         * Inclusive lower bound on `effective_at`, RFC 3339. **`axis=effective`
         * only** — on `axis=recorded` it is refused rather than ignored, because
         * the page there is ordered and bounded by commit position and a
         * business-date window would be a filter over the account's whole
         * history.
         */
        effective_from?: string;
        /**
         * EXCLUSIVE upper bound on `effective_at`, RFC 3339 — half-open, as every
         * range on this surface is (ADR-0011 §A3). `axis=effective` only.
         */
        effective_to?: string;
        /**
         * How many entries at most, 1–1000. Omitted means 100. A value outside
         * the window is REFUSED rather than clamped, exactly as on
         * `GET /v1/accounts`.
         */
        limit?: number;
        /**
         * The `next_after` an earlier page of **this same axis** answered with,
         * sent back unchanged. It is the last row's ordering key — `xact_id` and
         * entry id on the recorded axis, the business date as well on the
         * effective one — and a key of the other axis is refused rather than
         * used as a bound of an order it does not name.
         *
         * **It is never `account_seq`**, and that is the trap worth naming:
         * `uq_entries__account_seq` is per `(tenant, account, stripe, seq)`, so
         * on a striped account the counter is not a total order and paging by it
         * would interleave two counters and silently drop or repeat rows
         * (ADR-0023). The number is returned on every entry — it is what a drift
         * check walks — and it does not order the page.
         */
        after?: string;
    };
    url: '/v1/accounts/{account_id}/entries';
};

export type GetAccountStatementErrors = {
    /**
     * A required query parameter is missing — `tenant_id`, or the `axis` this endpoint will not choose for you — or a value would not deserialize into its documented type, including an `account_id` path segment that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * No such account on this book. `type` is `account_unknown` — note that the write path returns 422 under this same `type`, deliberately: there the caller must change the request, here the resource does not exist. An account that exists with no entries is a 200 with an empty page, and only the account register can draw that distinction (ADR-0019).
     */
    404: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `axis` that is not `recorded` or `effective`; an `effective_from` or `effective_to` that is not an RFC 3339 instant, or either of them on `axis=recorded`, where the page is bounded by commit position; a `limit` outside 1–1000, zero and negative included — refused rather than clamped; an `after` that is not a page key of the axis being paged; or a `cursor` that is not an `xid8` at all), `cursor_invalid` (a legal `xid8` above this cluster's horizon or at or below the book's oldest entry), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetAccountStatementError = GetAccountStatementErrors[keyof GetAccountStatementErrors];

export type GetAccountStatementResponses = {
    /**
     * One page of the account's entries, in the axis's order, with the cursor the page was pinned at and the key of the next page. **The two axes answer the same SET in different ORDERS**, and a backdated entry is where they disagree: it sits in its own past on the effective axis and at the end of the recorded one. An account that exists and has no entries in range answers an empty list, never a 404. **The page is NOT posted-only**: a pending hold writes entries and they are here, each carrying its transaction's `status`, so a reader can tell a settled row from a claim — which `GET /v1/accounts/{account_id}/balance` cannot show, because it reads the balance cache and that means posted (ADR-0010). Summing this page and comparing it to that balance requires dropping the `pending` rows first.
     */
    200: AccountStatementRead;
};

export type GetAccountStatementResponse = GetAccountStatementResponses[keyof GetAccountStatementResponses];

export type GetCursorData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The book to read. **The horizon is the CLUSTER's**, not this book's —
         * `report_cursor()` is `pg_snapshot_xmin` — so two tenants are answered
         * the same number. It is required anyway so that this route runs the
         * identical scoped read bracket every other read runs, rather than being
         * the one read that reaches the database unscoped.
         */
        tenant_id: string;
    };
    url: '/v1/cursor';
};

export type GetCursorErrors = {
    /**
     * The `tenant_id` query parameter is missing, or would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is `tenant_mismatch` — the `tenant_id` asked about is not the scope the read path set on the session. Vacuous today by construction and declared anyway (ADR-0019).
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetCursorError = GetCursorErrors[keyof GetCursorErrors];

export type GetCursorResponses = {
    /**
     * The current commit horizon — one `SELECT report_cursor()`, no report. Store it and send it back as `cursor` to pin a report here. **It is the cluster's horizon and not this tenant's**: `report_cursor()` is `pg_snapshot_xmin`, so every tenant is answered the same number, and `tenant_id` is required for the scoping every other read has rather than because the answer depends on it.
     */
    200: CursorRead;
};

export type GetCursorResponse = GetCursorResponses[keyof GetCursorResponses];

export type DefinePeriodData = {
    body: PeriodBody;
    path?: never;
    query?: never;
    url: '/v1/periods';
};

export type DefinePeriodErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written. `type` is one of: `invalid_request` (a precondition on the body failed — an `ends_at` not after `starts_at`, a blank tenant, code or zone — or a field failed to deserialize into its documented type, an instant that is not RFC 3339 included), `idempotency_key_reused` (same key, different body — send a new key, or resend the original request unchanged; the key namespace is shared with the other writes, deliberately, because it is the same spine), `period_overlaps` (`ex_periods__no_overlap` — this tenant already has a period covering part of this one; the API surfaces the exclusion constraint rather than re-checking it, because no read before the insert can see an uncommitted rival), `period_exists` (`pk_periods` — this book already holds a period under this code; it is checked BEFORE the exclusion index, so it is what redefining a code actually meets), `period_zone_unknown` (`ck_periods__tz_known` — the server's tzdata does not carry this zone name).
     */
    422: ErrorBody;
    /**
     * The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type DefinePeriodError = DefinePeriodErrors[keyof DefinePeriodErrors];

export type DefinePeriodResponses = {
    /**
     * Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2).
     */
    200: PeriodCreated;
    /**
     * Defined: this call claimed the idempotency key and wrote the period and its event atomically. The answer carries the period as the register holds it — the resolved instants a report will filter on, read back from the insert (ADR-0024).
     */
    201: PeriodCreated;
};

export type DefinePeriodResponse = DefinePeriodResponses[keyof DefinePeriodResponses];

export type ClosePeriodData = {
    body: ClosePeriodBody;
    path: {
        /**
         * The period's label, as `POST /v1/periods` defined it.
         */
        code: string;
    };
    query?: never;
    url: '/v1/periods/{code}/close';
};

export type ClosePeriodErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written — the transaction, its entries, every swept account's balance row, the close record and the checkpoint all roll back together. `type` is one of: `period_unknown` (`{code}` names no period on this tenant; refused before the derived key is claimed, which matters because a derived key burnt by a refusal could never be retried under another name), `period_already_closed` (`pk_closes` — this period and currency are closed, and a close happens once; correct one with a later posting, since reversing a close is refused by ADR-0016), `retained_earnings_unknown` (this book holds no `retained_earnings` house account in this currency, so the sweep has no destination — there is no Income Summary account to fall back on, ADR-0011 §2), `invalid_request` (a blank tenant or code, a currency that is not three uppercase letters), `idempotency_key_reused` (the derived key string is held by a request with a different body).
     */
    422: ErrorBody;
    /**
     * The close failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type ClosePeriodError = ClosePeriodErrors[keyof ClosePeriodErrors];

export type ClosePeriodResponses = {
    /**
     * Closed. In ONE database transaction, in this order (ADR-0024): the deterministic idempotency key `tenant:close:period:currency` is claimed; the `period_close` transaction is written — one posting per temporary account holding a non-zero position, destination `retained_earnings`, dated `ends_at - 1 microsecond`; the close record naming that transaction and its cursor; and THEN the checkpoint, one row per account, because the closing entries must exist before they can be admitted to their own checkpoint by identity (ADR-0020). A period with nothing to sweep closes cleanly and answers an empty `swept`.
     */
    201: PeriodClosedRead;
};

export type ClosePeriodResponse = ClosePeriodResponses[keyof ClosePeriodResponses];

export type GetBalanceSheetData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * The instant to report the position as at, RFC 3339. **This is a
         * period's `ends_at`, never a business date**: the predicate is
         * `effective_at < as_of`, so a business date returns the position at the
         * START of that day and silently loses a day at every period boundary
         * (ADR-0019). Nothing raises, and the number is plausible.
         */
        as_of: string;
        cursor?: string;
        /**
         * The chart version to present at. Omitted means the version the book is
         * on now, resolved by the read path and reported back in
         * `chart_version` — never left to the SQL default, which resolves at run
         * time (ADR-0019 B6).
         */
        chart_version?: number;
    };
    url: '/v1/reports/balance-sheet';
};

export type GetBalanceSheetErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `as_of` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown` (no such version, or no chart has been seeded at all), `chart_version_incomplete` (the version does not present every account type with posted entries as at this instant — refused rather than silently dropping a sub-book from a face that would still balance), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetBalanceSheetError = GetBalanceSheetErrors[keyof GetBalanceSheetErrors];

export type GetBalanceSheetResponses = {
    /**
     * The face, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019).
     */
    200: StatementRead;
};

export type GetBalanceSheetResponse = GetBalanceSheetResponses[keyof GetBalanceSheetResponses];

export type GetIncomeStatementData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * Inclusive lower bound on `effective_at`, RFC 3339.
         */
        effective_from: string;
        /**
         * EXCLUSIVE upper bound on `effective_at`, RFC 3339.
         */
        effective_to: string;
        cursor?: string;
        chart_version?: number;
    };
    url: '/v1/reports/income-statement';
};

export type GetIncomeStatementErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown`, `chart_version_incomplete` (the version does not present every account type with posted entries in this window), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetIncomeStatementError = GetIncomeStatementErrors[keyof GetIncomeStatementErrors];

export type GetIncomeStatementResponses = {
    /**
     * The statement, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019).
     */
    200: StatementRead;
};

export type GetIncomeStatementResponse = GetIncomeStatementResponses[keyof GetIncomeStatementResponses];

export type GetTrialBalanceData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * Inclusive lower bound on `effective_at`, RFC 3339.
         */
        effective_from: string;
        /**
         * EXCLUSIVE upper bound on `effective_at`, RFC 3339 — the range is
         * half-open, as it is on all three report functions (ADR-0011 §A3).
         */
        effective_to: string;
        /**
         * The commit position to pin the report to — a `pinned_cursor` from an
         * earlier report. Omit it and one is pinned server-side and returned.
         */
        cursor?: string;
    };
    url: '/v1/reports/trial-balance';
};

export type GetTrialBalanceErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8` at all), `cursor_invalid` (a syntactically valid `xid8` that is above this cluster's horizon or at or below the book's oldest entry — `-1` wraps to the maximum and would return the entire UNPINNED book, `0` would return an all-zero balanced fabrication, and the database cannot refuse either), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019).
     */
    503: ErrorBody;
};

export type GetTrialBalanceError = GetTrialBalanceErrors[keyof GetTrialBalanceErrors];

export type GetTrialBalanceResponses = {
    /**
     * The trial balance, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019).
     */
    200: TrialBalanceRead;
};

export type GetTrialBalanceResponse = GetTrialBalanceResponses[keyof GetTrialBalanceResponses];

export type PostTransactionData = {
    body: TransactionBody;
    path?: never;
    query?: never;
    url: '/v1/transactions';
};

export type PostTransactionErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written. The caller must CHANGE the request to escape — which is why this is 422, not 400 or 409 (ADR-0013 §2). `type` is one of: `invalid_request` (a precondition on the body failed, or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key or resend the original request unchanged), `account_unknown` (a posting names an account that does not exist or does not hold that currency), `resolve_target_unknown` (`resolves_id` names no transaction on this tenant's book), `resolve_target_not_pending` (only a pending transaction can be resolved — its status never mutates), `reverse_target_unknown` (`reverses_id` names no transaction on this tenant's book), `reverse_target_not_reversible` (only an ordinary posting that is itself neither a resolution nor a reversal can be reversed), `target_already_superseded` (the named target already has its one supersession — resolved or reversed, either fate is final).
     */
    422: ErrorBody;
    /**
     * The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type PostTransactionError = PostTransactionErrors[keyof PostTransactionErrors];

export type PostTransactionResponses = {
    /**
     * Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2).
     */
    200: TransactionCreated;
    /**
     * Posted: this call claimed the idempotency key and wrote the transaction atomically.
     */
    201: TransactionCreated;
};

export type PostTransactionResponse = PostTransactionResponses[keyof PostTransactionResponses];

export type GetTransactionData = {
    body?: never;
    path: {
        /**
         * The transaction to read.
         */
        transaction_id: string;
    };
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
    };
    url: '/v1/transactions/{transaction_id}';
};

export type GetTransactionErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including a `transaction_id` path segment that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * No such transaction on this tenant's book. `type` is `transaction_unknown`. Note that an unknown TENANT is not 404 but 200-with-nothing on the report routes, and 404 here: there is no tenant registry to consult, so a wrong `tenant_id` is indistinguishable from a book that does not hold this transaction.
     */
    404: ErrorBody;
    /**
     * Refused. `type` is `tenant_mismatch` — the `tenant_id` asked about is not the scope the read path set on the session. Vacuous today by construction and declared anyway (ADR-0019).
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
    /**
     * The read exceeded the read pool's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019).
     */
    503: ErrorBody;
};

export type GetTransactionError = GetTransactionErrors[keyof GetTransactionErrors];

export type GetTransactionResponses = {
    /**
     * The transaction and its entries. `entries` is empty for a void — the zero-posting marker a reversal of a PENDING transaction writes (ADR-0016).
     */
    200: TransactionRead;
};

export type GetTransactionResponse = GetTransactionResponses[keyof GetTransactionResponses];
