// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * One account's posted balance.
 */
export type AccountBalanceRead = {
    account_id: string;
    /**
     * Always `now`. This endpoint reads the balance CACHE, which means
     * POSTED (ADR-0010), and pinning it to a cursor would be a second
     * definition of a balance — so the field is a statement of what the
     * number means rather than a parameter's echo.
     */
    as_of: string;
    currency: string;
    /**
     * Minor units, debit-positive, as an exact-integer decimal string. A
     * credit-normal account reads negative here and the presentation flip is
     * the reader's (ADR-0010).
     */
    posted_minor: string;
};

/**
 * The body of `POST /v1/accounts`.
 *
 * **What is NOT here is the design** (ADR-0021): there is no `category`, no
 * `normal_balance` and no `counterparty_scope`. `ledger_accounts` carries all
 * three as COPIES of the chart row, held honest by `fk_accounts__type` and
 * `fk_accounts__scope` — so a body that stated them could disagree with the
 * chart, and the caller would be handed a foreign-key error rather than an
 * answer. The caller names a `purpose` and the server reads the rest, which
 * makes a whole class of refusals unreachable rather than merely reported.
 */
export type AccountBody = {
    /**
     * ISO 4217 alphabetic code, three uppercase ASCII letters. One account
     * holds one currency.
     */
    currency: string;
    /**
     * Caller-supplied replay key, unique per tenant — and in the SAME
     * namespace a posting's key lives in, because it is the same spine
     * (`ledger_events`, ADR-0005). Sending the same key with the same body
     * replays the stored result; with a different body it is refused as
     * `idempotency_key_reused` (ADR-0013 §2), and that includes a key an
     * earlier POSTING claimed.
     */
    idempotency_key: string;
    /**
     * Caller's own JSON object, stored as given. It must BE an object:
     * `jsonb` would store a bare number as happily, and a metadata field
     * that is sometimes a scalar is a shape every reader has to defend
     * against.
     */
    metadata?: unknown;
    /**
     * Who owns it. Required for every `owner_type` except `house`, and
     * refused for `house` — `ck_accounts__house_has_no_owner`, answered as
     * `account_owner_mismatched`.
     */
    owner_id?: string | null;
    owner_type: OwnerTypeBody;
    /**
     * The account type, by its chart code — `customer_receivable`,
     * `fee_revenue`, and whatever else this deployment's chart carries. A
     * code `account_types` does not hold is `account_type_unknown`.
     */
    purpose: string;
    /**
     * How many stripes the writer spreads this account's balance row across,
     * 1–1024. Omitted means one. **A hint, not an invariant** (ADR-0013 §4):
     * a reader sums the stripe rows that exist, never the range `0..n-1`, so
     * nothing is stranded by getting it wrong — but no stripe ever appears
     * in a response, so this is the only place the number is spoken.
     */
    stripe_count?: number | null;
    /**
     * The book this account belongs to. Named in the body by decision
     * (ADR-0017): data scoping, never an identity claim.
     */
    tenant_id: string;
};

/**
 * The stored result of an accepted opening: the event, and the account it
 * caused.
 */
export type AccountCreated = {
    /**
     * The account. Never null, unlike a posting's `transaction_id`: an
     * accepted opening always wrote one, and a replay finds it by the
     * natural key its own body names.
     */
    account_id: string;
    /**
     * The event row this call claimed — or, on a replay, the one it found.
     * Opening an account writes an EVENT and no ledger transaction, which is
     * the case ADR-0005 justified the event log by.
     */
    event_id: string;
};

/**
 * One page of the account register.
 */
export type AccountListRead = {
    /**
     * The page, in creation order — `id` is `uuidv7()`, so ordering by it
     * orders by when each account was opened.
     *
     * **An empty list is a legitimate answer** and never a 404: it is what
     * an unknown tenant, a typo'd tenant, a tenant with no accounts and a
     * reader scoped elsewhere all produce, and two of those are the
     * fail-closed path working correctly (ADR-0019).
     */
    accounts: Array<AccountRead>;
    /**
     * The `after` to send for the next page, or `null` when this page did
     * not fill. **A full page means "there may be more", never "there is"**:
     * the alternative is reading one row past every page to be certain, and
     * a caller that follows this key to an empty page has learnt the same
     * thing one request later.
     */
    next_after: string | null;
};

/**
 * One account, as the register holds it.
 *
 * **No balance, and that is contract** (ADR-0021): balances are per currency
 * and per stripe, so a balance per row would be N+1, and
 * `GET /v1/accounts/{account_id}/balance` answers that question one account
 * at a time and exactly.
 */
export type AccountRead = {
    account_id: string;
    /**
     * `asset`, `liability`, `equity`, `revenue` or `expense` — the chart's,
     * copied onto the account and held honest by `fk_accounts__type`.
     */
    category: string;
    /**
     * `none`, `shared` or `per_shard` — whether this type's positions may be
     * summed for reporting, and the reason a `per_shard` type cannot live in
     * a house account (ADR-0012).
     */
    counterparty_scope: string;
    /**
     * When the account was opened — the database's clock.
     */
    created_at: string;
    currency: string;
    /**
     * `debit` or `credit`. **Not derivable from `category`**: a loss
     * allowance is an asset with a credit normal balance, which is why the
     * schema stores both.
     */
    normal_balance: string;
    /**
     * `null` on a house account, which is the ledger's own side and has no
     * owner.
     */
    owner_id: string | null;
    /**
     * `company`, `platform`, `bank_account` or `house`.
     */
    owner_type: string;
    /**
     * The account type, by its chart code.
     */
    purpose: string;
    /**
     * How many stripes the writer spreads this account's balance row across.
     * **The one place a stripe count is spoken** — no stripe VALUE appears
     * in any response (ADR-0013 §4), and this is the hint, not a position.
     */
    stripe_count: number;
};

/**
 * One leg. `amount_minor` is a JSON number here and a decimal STRING on
 * every report, and the asymmetry is deliberate (ADR-0019): a single posting
 * is bounded by its column, and only an aggregate can exceed what a JSON
 * number carries exactly.
 */
export type EntryRead = {
    account_id: string;
    /**
     * The account's own gapless sequence number for this leg. The counter is
     * per `(account, stripe)` — documented, never exposed: no stripe appears
     * in any response (ADR-0013 §4).
     */
    account_seq: number;
    amount_minor: number;
    currency: string;
    /**
     * `debit` or `credit`. Direction carries the sign; the amount never does.
     */
    direction: string;
};

/**
 * The error body: a stable machine-readable `type`, prose in `detail`.
 */
export type ErrorBody = {
    /**
     * Human-readable explanation. Not stable; do not parse.
     */
    detail: string;
    /**
     * Stable machine-readable identifier. Parse this, never `detail`.
     */
    type: string;
};

/**
 * Who an account belongs to — the schema's `account_owner_type`. `house` is
 * the ledger's own side of a movement and is the one value that carries NO
 * `owner_id`; the other three name one.
 */
export type OwnerTypeBody = 'company' | 'platform' | 'bank_account' | 'house';

/**
 * One movement of money: `amount_minor` leaves `source` and arrives at
 * `destination`. Direction is carried by the pair, never by a sign.
 */
export type PostingBody = {
    /**
     * Minor units of `currency`. Strictly positive.
     */
    amount_minor: number;
    /**
     * ISO 4217 alphabetic code, three uppercase ASCII letters.
     */
    currency: string;
    /**
     * Account the amount arrives at.
     */
    destination: string;
    /**
     * Account the amount leaves.
     */
    source: string;
};

/**
 * One line of a statement face.
 */
export type StatementLineRead = {
    /**
     * Minor units, as an exact-integer decimal string — **not a JSON
     * number**. A report total is an aggregate and can exceed what a JSON
     * number carries exactly, which would be rounded silently by the parser
     * at the other end (ADR-0019). It costs every caller one parse,
     * deliberately.
     */
    amount_minor: string;
    caption: string;
    currency: string;
    /**
     * The chart's line code.
     */
    fs_line: string;
    /**
     * Which side of the face this line belongs to.
     */
    side: string;
    /**
     * The chart's ordering, not a row number.
     */
    sort_order: number;
};

/**
 * A statement face — the same shape for the balance sheet and the income
 * statement, because the two functions return the same columns.
 */
export type StatementRead = {
    /**
     * The chart version this face was presented at — always named, never
     * defaulted. **The residual, stated** (ADR-0019 B6): naming a version
     * pins the presentation only BELOW `max(version)`, because
     * `refuse_stale_chart_version()` freezes history and not the present.
     */
    chart_version: number;
    /**
     * The face, in the chart's own `sort_order`.
     *
     * **What is reproducible at a stored cursor, and what is not**
     * (ADR-0019 B7): the AMOUNTS are; the ROW SET is not. The lines are
     * enumerated from tables that carry no `xact_id` — one new account with
     * nothing posted to it added ten balance-sheet rows at a fixed cursor,
     * every pre-existing amount byte-identical. And an income statement's
     * amounts carry one carve-out of their own: a period close inserted
     * AFTER a statement is issued retroactively removes that transaction's
     * entries from it, because `ledger_period_closes` has no commit position.
     */
    lines: Array<StatementLineRead>;
    pinned_cursor: string;
};

/**
 * Whether the transaction lands on the books or records money that MAY
 * move. Status never mutates: a pending transaction becomes posted by a NEW
 * transaction naming it in `resolves_id`, never by an update (ADR-0016).
 */
export type StatusBody = 'pending' | 'posted';

/**
 * The body of `POST /v1/transactions`.
 */
export type TransactionBody = {
    /**
     * When the movement is deemed to have happened, RFC 3339. Required —
     * the writer will not invent a date — EXCEPT on a reversal, where
     * omission means "the target's own effective_at" (ADR-0016's soft
     * convention). A supplied date is taken as given, including one below
     * the target's; the cost of that window is recorded in ADR-0016.
     */
    effective_at?: string | null;
    /**
     * Caller-supplied replay key, unique per tenant. Sending the same key
     * with the same body replays the stored result; with a different body it
     * is refused as `idempotency_key_reused` (ADR-0013 §2).
     */
    idempotency_key: string;
    /**
     * At least one posting — except on a reversal, which must carry NONE:
     * the server derives the mirror from the target.
     */
    postings?: Array<PostingBody>;
    /**
     * The PENDING transaction this one resolves — pending → posted is this
     * new, posted transaction, never an update to the original (ADR-0016).
     * The resolution's postings need not mirror the pending amounts (a
     * partial capture resolves with less); a resolving transaction cannot
     * itself be pending.
     */
    resolves_id?: string | null;
    /**
     * The transaction this one reverses — operational undo, as a NEW
     * posted transaction (ADR-0016): a posted target is mirrored in full
     * (same legs, directions flipped, derived by the server — send NO
     * postings), and a pending target is voided by a zero-posting marker.
     * The target must be an ordinary posting on this tenant's book,
     * itself neither a resolution nor a reversal, and not already
     * superseded.
     */
    reverses_id?: string | null;
    status?: null | StatusBody;
    /**
     * The book this transaction belongs to. Named in the body by decision
     * (ADR-0017): data scoping, never an identity claim — the trust story is
     * the deployment perimeter's, and authenticating callers is the
     * deployer's layer.
     */
    tenant_id: string;
};

/**
 * The stored result of an accepted operation: the event, and the transaction
 * it caused.
 */
export type TransactionCreated = {
    /**
     * The event row this call claimed — or, on a replay, the one it found.
     */
    event_id: string;
    /**
     * The transaction the event caused. Nullable by contract: most accepted
     * operations write no transaction at all (ADR-0013 §2). This endpoint
     * always writes one, but a replay re-renders whatever was stored.
     */
    transaction_id: string | null;
};

/**
 * A transaction as the book holds it, with its entries.
 */
export type TransactionRead = {
    /**
     * When the movement is deemed to have happened — the caller's clock.
     */
    effective_at: string;
    /**
     * The legs. **Empty is a real answer**: a reversal of a pending
     * transaction is a zero-posting void marker (ADR-0016).
     */
    entries: Array<EntryRead>;
    /**
     * The event that caused this transaction.
     */
    event_id: string;
    /**
     * `posting` for an ordinary transaction, `period_close` for a close.
     */
    kind: string;
    /**
     * When the row was written — the database's clock. The two axes are
     * different questions (ADR-0006) and neither is derivable from the other.
     */
    recorded_at: string;
    /**
     * The pending transaction this one resolved, if it is a resolution.
     */
    resolves_id: string | null;
    /**
     * The transaction this one reversed, if it is a reversal.
     */
    reverses_id: string | null;
    /**
     * `pending` or `posted`. **It never mutates**: a pending transaction
     * becomes posted by a NEW transaction naming it in `resolves_id`
     * (ADR-0016), so a `pending` here is what was recorded and not a stage
     * this row is passing through.
     */
    status: string;
    transaction_id: string;
};

/**
 * The trial balance, and the cursor it was pinned at.
 */
export type TrialBalanceRead = {
    /**
     * The commit position this report ran at — supplied or server-pinned.
     * Store it to re-run this exact report; a decimal string, because an
     * `xid8` is a 64-bit unsigned value and JSON numbers are not.
     */
    pinned_cursor: string;
    /**
     * One row per `(account, currency)` with any activity in the window.
     * **An empty list is a legitimate answer** and never a 404: it is what
     * an unknown tenant, a typo'd tenant, a tenant with no accounts, a
     * reader scoped elsewhere and an unscoped session all produce, and two
     * of those five are the fail-closed path working correctly (ADR-0019).
     */
    rows: Array<TrialBalanceRowRead>;
};

/**
 * One `(account, currency)` of the trial balance. Every amount is a decimal
 * string.
 */
export type TrialBalanceRowRead = {
    account_id: string;
    /**
     * The ARITHMETIC value — roll up with this one. `normal_balance` never
     * enters it, so a contra account carries its own sign instead of being
     * flipped twice.
     */
    balance_debit_positive: string;
    /**
     * `asset`, `liability`, `equity`, `revenue` or `expense`.
     */
    category: string;
    /**
     * Gross credits in the window.
     */
    credits: string;
    currency: string;
    /**
     * Gross debits in the window.
     */
    debits: string;
    /**
     * The account type — the chart's code, e.g. `operating_cash`.
     */
    purpose: string;
};

export type ListAccountsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
        /**
         * How many accounts at most, 1–1000. Omitted means 100. A value outside
         * the window is REFUSED rather than clamped: a clamped page is an answer
         * to a question the caller did not ask, and nothing on the wire would
         * say so.
         */
        limit?: number;
        /**
         * The last `account_id` of the previous page — send back the
         * `next_after` an earlier page answered with. Keyset, never an offset
         * (ADR-0021): an offset shifts under concurrent inserts, so a caller
         * paging a growing book silently skips rows.
         */
        after?: string;
        /**
         * Equality on the chart code. **Equality, not search**: no pattern
         * matching and no free text.
         */
        purpose?: string;
        /**
         * Equality on the owner. It selects no house accounts, which have no
         * owner at all.
         */
        owner_id?: string;
    };
    url: '/v1/accounts';
};

export type ListAccountsErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including an `after` that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (a `limit` outside 1–1000, zero or negative included — refused rather than clamped) or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
    /**
     * One page of the account register, in creation order. An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019).
     */
    200: AccountListRead;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type OpenAccountData = {
    body: AccountBody;
    path?: never;
    query?: never;
    url: '/v1/accounts';
};

export type OpenAccountErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written. Every `type` below is a constraint the schema already holds, refused by name rather than surfaced as a database error (ADR-0021). `type` is one of: `invalid_request` (a precondition on the body failed — a `stripe_count` outside 1–1024, a currency that is not three uppercase letters, a blank tenant, metadata that is not an object — or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key, or resend the original request unchanged; the key namespace is shared with `POST /v1/transactions`, deliberately, because it is the same spine), `account_type_unknown` (`purpose` names no row in this deployment's chart), `account_exists` (`uq_accounts__owned` or `uq_accounts__house` already holds this account; the refusal does not say whose, because within one tenant a collision is always the caller's own), `account_owner_mismatched` (`ck_accounts__house_has_no_owner` — a house account has no owner and an owned account must have one), `account_type_requires_an_owner` (`ck_accounts__per_shard_is_owned` — a type whose split key IS the counterparty cannot be held in a house account, because such an account nets every counterparty at write time and no report can recover it).
     */
    422: ErrorBody;
    /**
     * The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type OpenAccountError = OpenAccountErrors[keyof OpenAccountErrors];

export type OpenAccountResponses = {
    /**
     * Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2).
     */
    200: AccountCreated;
    /**
     * Opened: this call claimed the idempotency key and wrote the account and its event atomically.
     */
    201: AccountCreated;
};

export type OpenAccountResponse = OpenAccountResponses[keyof OpenAccountResponses];

export type GetAccountBalanceData = {
    body?: never;
    path: {
        /**
         * The account to read.
         */
        account_id: string;
    };
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
        /**
         * ISO 4217 alphabetic code.
         */
        currency: string;
    };
    url: '/v1/accounts/{account_id}/balance';
};

export type GetAccountBalanceErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including an `account_id` path segment that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * No such account on this book, or the account does not hold that currency. `type` is `account_unknown` — note that the write path returns 422 under this same `type`, deliberately: there the caller must change the request, here the resource does not exist.
     */
    404: ErrorBody;
    /**
     * Refused. `type` is `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetAccountBalanceError = GetAccountBalanceErrors[keyof GetAccountBalanceErrors];

export type GetAccountBalanceResponses = {
    /**
     * The posted balance, summed over the account's balance rows. An account that exists and has never been written answers `"0"` — which is why this endpoint reads the account register and not only the balance cache (ADR-0019).
     */
    200: AccountBalanceRead;
};

export type GetAccountBalanceResponse = GetAccountBalanceResponses[keyof GetAccountBalanceResponses];

export type GetBalanceSheetData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * The instant to report the position as at, RFC 3339. **This is a
         * period's `ends_at`, never a business date**: the predicate is
         * `effective_at < as_of`, so a business date returns the position at the
         * START of that day and silently loses a day at every period boundary
         * (ADR-0019). Nothing raises, and the number is plausible.
         */
        as_of: string;
        cursor?: string;
        /**
         * The chart version to present at. Omitted means the version the book is
         * on now, resolved by the read path and reported back in
         * `chart_version` — never left to the SQL default, which resolves at run
         * time (ADR-0019 B6).
         */
        chart_version?: number;
    };
    url: '/v1/reports/balance-sheet';
};

export type GetBalanceSheetErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `as_of` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown` (no such version, or no chart has been seeded at all), `chart_version_incomplete` (the version does not present every account type with posted entries as at this instant — refused rather than silently dropping a sub-book from a face that would still balance), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetBalanceSheetError = GetBalanceSheetErrors[keyof GetBalanceSheetErrors];

export type GetBalanceSheetResponses = {
    /**
     * The face, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019).
     */
    200: StatementRead;
};

export type GetBalanceSheetResponse = GetBalanceSheetResponses[keyof GetBalanceSheetResponses];

export type GetIncomeStatementData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * Inclusive lower bound on `effective_at`, RFC 3339.
         */
        effective_from: string;
        /**
         * EXCLUSIVE upper bound on `effective_at`, RFC 3339.
         */
        effective_to: string;
        cursor?: string;
        chart_version?: number;
    };
    url: '/v1/reports/income-statement';
};

export type GetIncomeStatementErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown`, `chart_version_incomplete` (the version does not present every account type with posted entries in this window), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`.
     */
    503: ErrorBody;
};

export type GetIncomeStatementError = GetIncomeStatementErrors[keyof GetIncomeStatementErrors];

export type GetIncomeStatementResponses = {
    /**
     * The statement, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019).
     */
    200: StatementRead;
};

export type GetIncomeStatementResponse = GetIncomeStatementResponses[keyof GetIncomeStatementResponses];

export type GetTrialBalanceData = {
    body?: never;
    path?: never;
    query: {
        tenant_id: string;
        /**
         * Inclusive lower bound on `effective_at`, RFC 3339.
         */
        effective_from: string;
        /**
         * EXCLUSIVE upper bound on `effective_at`, RFC 3339 — the range is
         * half-open, as it is on all three report functions (ADR-0011 §A3).
         */
        effective_to: string;
        /**
         * The commit position to pin the report to — a `pinned_cursor` from an
         * earlier report. Omit it and one is pinned server-side and returned.
         */
        cursor?: string;
    };
    url: '/v1/reports/trial-balance';
};

export type GetTrialBalanceErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8` at all), `cursor_invalid` (a syntactically valid `xid8` that is above this cluster's horizon or at or below the book's oldest entry — `-1` wraps to the maximum and would return the entire UNPINNED book, `0` would return an all-zero balanced fabrication, and the database cannot refuse either), or `tenant_mismatch`.
     */
    422: ErrorBody;
    /**
     * The report failed. `type` is `internal`.
     */
    500: ErrorBody;
    /**
     * The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019).
     */
    503: ErrorBody;
};

export type GetTrialBalanceError = GetTrialBalanceErrors[keyof GetTrialBalanceErrors];

export type GetTrialBalanceResponses = {
    /**
     * The trial balance, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019).
     */
    200: TrialBalanceRead;
};

export type GetTrialBalanceResponse = GetTrialBalanceResponses[keyof GetTrialBalanceResponses];

export type PostTransactionData = {
    body: TransactionBody;
    path?: never;
    query?: never;
    url: '/v1/transactions';
};

export type PostTransactionErrors = {
    /**
     * The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message.
     */
    400: ErrorBody;
    /**
     * The request body exceeds the size limit. `type` is `invalid_request`.
     */
    413: ErrorBody;
    /**
     * The request's `Content-Type` is not `application/json`. `type` is `invalid_request`.
     */
    415: ErrorBody;
    /**
     * Refused, and nothing was written. The caller must CHANGE the request to escape — which is why this is 422, not 400 or 409 (ADR-0013 §2). `type` is one of: `invalid_request` (a precondition on the body failed, or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key or resend the original request unchanged), `account_unknown` (a posting names an account that does not exist or does not hold that currency), `resolve_target_unknown` (`resolves_id` names no transaction on this tenant's book), `resolve_target_not_pending` (only a pending transaction can be resolved — its status never mutates), `reverse_target_unknown` (`reverses_id` names no transaction on this tenant's book), `reverse_target_not_reversible` (only an ordinary posting that is itself neither a resolution nor a reversal can be reversed), `target_already_superseded` (the named target already has its one supersession — resolved or reversed, either fate is final).
     */
    422: ErrorBody;
    /**
     * The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
};

export type PostTransactionError = PostTransactionErrors[keyof PostTransactionErrors];

export type PostTransactionResponses = {
    /**
     * Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2).
     */
    200: TransactionCreated;
    /**
     * Posted: this call claimed the idempotency key and wrote the transaction atomically.
     */
    201: TransactionCreated;
};

export type PostTransactionResponse = PostTransactionResponses[keyof PostTransactionResponses];

export type GetTransactionData = {
    body?: never;
    path: {
        /**
         * The transaction to read.
         */
        transaction_id: string;
    };
    query: {
        /**
         * The book to read.
         */
        tenant_id: string;
    };
    url: '/v1/transactions/{transaction_id}';
};

export type GetTransactionErrors = {
    /**
     * A required query parameter is missing, or a value would not deserialize into its documented type — including a `transaction_id` path segment that is not a UUID. `type` is `invalid_request`.
     */
    400: ErrorBody;
    /**
     * No such transaction on this tenant's book. `type` is `transaction_unknown`. Note that an unknown TENANT is not 404 but 200-with-nothing on the report routes, and 404 here: there is no tenant registry to consult, so a wrong `tenant_id` is indistinguishable from a book that does not hold this transaction.
     */
    404: ErrorBody;
    /**
     * Refused. `type` is `tenant_mismatch` — the `tenant_id` asked about is not the scope the read path set on the session. Vacuous today by construction and declared anyway (ADR-0019).
     */
    422: ErrorBody;
    /**
     * The read failed. `type` is `internal`, and the caller gets no internals — the operator's log has the error.
     */
    500: ErrorBody;
    /**
     * The read exceeded the read pool's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019).
     */
    503: ErrorBody;
};

export type GetTransactionError = GetTransactionErrors[keyof GetTransactionErrors];

export type GetTransactionResponses = {
    /**
     * The transaction and its entries. `entries` is empty for a void — the zero-posting marker a reversal of a PENDING transaction writes (ADR-0016).
     */
    200: TransactionRead;
};

export type GetTransactionResponse = GetTransactionResponses[keyof GetTransactionResponses];
