#!/usr/bin/env python3
"""10_copy_vs_insert.py -- generate 10_copy_vs_insert.sql.

The RLS decision turns on one assumption nobody measured: that `COPY FROM` is
load-bearing on the batched write path, so RLS and batching are mutually
exclusive. COPY beats a multi-row INSERT at thousands of rows. Spike 003's best
coalesced batch was 25-100 postings. Those are different regimes, and the whole
question is which one we are in.

This emits a psql script that inserts the SAME rows into `ledger_entries` three
ways at three batch sizes, with \\timing on, repeated. Parse the output with
10_run.sh.

  COPY        -- COPY ledger_entries (...) FROM STDIN
  VALUES      -- one INSERT with N value tuples
  UNNEST      -- INSERT ... SELECT ... FROM unnest(array, array, ...)
"""
import sys

TENANT = 't1'
TXN = 'faceface-0000-0000-0000-000000000001'
EV = 'facefeed-0000-0000-0000-000000000001'
ACCT = '11111111-0000-0000-0000-0000000000aa'
EFF = '2026-08-20T00:00:00Z'
SIZES = [25, 100, 1000, 10000]
REPS = 5

out = []
w = out.append

w(f"""-- GENERATED by 10_copy_vs_insert.py -- do not edit, regenerate.
\\set ON_ERROR_STOP on
\\pset pager off

-- a dedicated account and transaction, so nothing else in this directory shifts
INSERT INTO ledger_accounts (tenant_id, id, owner_type, owner_id, purpose, category, normal_balance, currency)
VALUES ('{TENANT}','{ACCT}','house',NULL,'fee_revenue','revenue','credit','USD')
ON CONFLICT DO NOTHING;
INSERT INTO ledger_account_balances (tenant_id, account_id, currency)
VALUES ('{TENANT}','{ACCT}','USD') ON CONFLICT DO NOTHING;
INSERT INTO ledger_events (tenant_id, id, kind, source, idempotency_key, idempotency_hash, payload, effective_at)
VALUES ('{TENANT}','{EV}','bulk','internal','bulk-1', sha256('{{}}'), '{{}}', '{EFF}')
ON CONFLICT DO NOTHING;
INSERT INTO ledger_transactions (tenant_id, id, event_id, kind, status, effective_at)
VALUES ('{TENANT}','{TXN}','{EV}','bulk','posted','{EFF}') ON CONFLICT DO NOTHING;

\\timing on
""")

seq = 0
for n in SIZES:
    for rep in range(REPS):
        for method in ('COPY', 'VALUES', 'UNNEST'):
            lo = seq + 1
            seq += n
            w(f"\\echo '@@ {method} {n} rep{rep+1}'")
            if method == 'COPY':
                w(f"COPY ledger_entries (tenant_id, transaction_id, account_id, direction, "
                  f"amount_minor, currency, account_seq, effective_at) FROM STDIN WITH (FORMAT csv);")
                for i in range(n):
                    w(f"{TENANT},{TXN},{ACCT},credit,1,USD,{lo+i},{EFF}")
                w("\\.")
            elif method == 'VALUES':
                tup = ",".join(
                    f"('{TENANT}','{TXN}','{ACCT}','credit',1,'USD',{lo+i},'{EFF}')"
                    for i in range(n))
                w("INSERT INTO ledger_entries (tenant_id, transaction_id, account_id, direction, "
                  f"amount_minor, currency, account_seq, effective_at) VALUES {tup};")
            else:
                seqs = ",".join(str(lo + i) for i in range(n))
                w("INSERT INTO ledger_entries (tenant_id, transaction_id, account_id, direction, "
                  "amount_minor, currency, account_seq, effective_at) "
                  f"SELECT '{TENANT}','{TXN}','{ACCT}','credit',1,'USD', s, '{EFF}' "
                  f"FROM unnest(ARRAY[{seqs}]::bigint[]) s;")

w("\\timing off")
w(f"SELECT count(*) AS entries_written FROM ledger_entries WHERE account_id='{ACCT}';")

open(sys.argv[1] if len(sys.argv) > 1 else '10_copy_vs_insert.sql', 'w').write("\n".join(out) + "\n")
