//! The committed `crates/api/openapi.json` is an artifact with a drift
//! refusal, the same instinct as the schema snapshot (ADR-0007 §2): the spec
//! is generated from the annotations, committed, and this test regenerates it
//! and compares bytes. The e2e conformance test holds the other half — that
//! the committed document matches the running router.
//!
//! Two tests, because a byte-diff against a committed file rests on emission
//! being DETERMINISTIC, and that is a different property from the drift the
//! diff reports: non-deterministic emission failed the drift test with a
//! message about the annotations having changed — the wrong story about the
//! wrong file. Held apart, each failure names itself.

/// Where the committed spec lives: the bytes the drift test compares against,
/// and the file its regeneration branch rewrites.
const COMMITTED_AT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/openapi.json");

/// The committed document, by the bytes, with the remedy in the read error —
/// the file is absent on the very first regeneration, and on a checkout that
/// forgot to commit it.
fn the_committed_spec() -> Result<String, Box<dyn std::error::Error>> {
    std::fs::read_to_string(COMMITTED_AT).map_err(|e| {
        format!(
            "could not read {COMMITTED_AT}: {e} — regenerate it with \
             OPENLEDGER_WRITE_SPEC=1 cargo test -p api --test spec"
        )
        .into()
    })
}

/// Whether this run was asked to rewrite the committed spec instead of
/// comparing against it. An explicit opt-in, so a normal run can only ever
/// FAIL on drift, never paper over it by rewriting the file it was about to
/// compare.
fn asked_to_rewrite_the_committed_spec() -> bool {
    std::env::var_os("OPENLEDGER_WRITE_SPEC").is_some()
}

#[test]
fn two_spec_generations_in_one_process_are_byte_identical() -> Result<(), Box<dyn std::error::Error>>
{
    // What the byte-diff below rests on, asserted as itself: emission must be
    // deterministic for a byte comparison against a committed file to mean
    // anything. (Cross-process and cross-rebuild stability was measured in
    // spike 021; every CI run of the drift test, on a fresh build, re-checks
    // that against the committed bytes for real.)
    let generated = api::openapi_json()?;

    let generated_again = api::openapi_json()?;

    assert_eq!(
        generated, generated_again,
        "spec emission is not deterministic — two generations in one process disagree"
    );
    Ok(())
}

/// To regenerate the committed spec after changing the annotations:
///
/// ```text
/// OPENLEDGER_WRITE_SPEC=1 cargo test -p api --test spec
/// ```
///
/// then commit the rewritten `crates/api/openapi.json`.
#[test]
fn the_committed_spec_matches_the_code() -> Result<(), Box<dyn std::error::Error>> {
    let rewriting = asked_to_rewrite_the_committed_spec();

    let generated = api::openapi_json()?;

    // Under the opt-in the generated bytes BECOME the baseline instead of
    // being compared to it — the only branch, and it asserts nothing.
    if rewriting {
        std::fs::write(COMMITTED_AT, &generated)?;
        return Ok(());
    }
    assert_eq!(
        the_committed_spec()?,
        generated,
        "crates/api/openapi.json no longer matches the annotations; \
         regenerate it with OPENLEDGER_WRITE_SPEC=1 cargo test -p api --test spec \
         and commit the diff"
    );
    Ok(())
}
