/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the accounts on one book.
         * @description **ADR-0019 refused every listing; ADR-0021 withdraws that for accounts and
         *     keeps it for transactions.** ADR-0019's ground was that a listing *"needs
         *     an ordering and a page key this spike did not design"* — a *not yet*, not a
         *     *never* — and for accounts the ordering already exists: `pk_accounts` is
         *     `(tenant_id, id)` and `id` is `uuidv7()`, which is time-ordered and total.
         *     A TRANSACTION listing would still have to choose between the recorded and
         *     the effective axis, which is the one place a listing can be confidently
         *     wrong.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Open an account.
         * @description The response set below is this endpoint's real one, not a shared error
         *     enum's: the six 422 `type`s named are exactly the ones the writer can
         *     produce here. `account_exists` never appears on the posting endpoint and
         *     `account_unknown` never appears here, which is precisely why opening
         *     carries its own error type in the core (ADR-0021).
         */
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one account's posted balance.
         * @description **No cursor, and that is the contract**: this reads the balance cache,
         *     which means POSTED, NOW (ADR-0010). Pinning it to a cursor would be a
         *     second definition of a balance, and the journal-based answer is the trial
         *     balance next door.
         */
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the balance-sheet face as at one instant. */
        get: operations["getBalanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the income statement over a half-open effective range. */
        get: operations["getIncomeStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the trial balance.
         * @description **One endpoint serves both of ADR-0006's time axes, by parameter and never
         *     by a mode flag**: the RECORDED axis is the cursor — widen the range and
         *     vary it — and the EFFECTIVE axis is the range — fix the cursor and vary
         *     it. Two resources for two parameters of one function is Formance's
         *     `pit`-resolves-to-six-columns mistake (ADR-0019 C2).
         */
        get: operations["getTrialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a transaction.
         * @description The response set below is this endpoint's real one, not a shared error
         *     enum's: the eight 422 `type`s named are exactly the ones the writer can
         *     produce here, and nothing else is documented (spike 021 found both
         *     candidate libraries fanning shared enums across statuses their endpoints
         *     cannot return — the fix is to declare per endpoint, so this project
         *     does).
         */
        post: operations["postTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a transaction back.
         * @description No cursor and no chart version: a transaction and its entries are
         *     immutable (`ck_txn__append_only` and `ck_entries__append_only`, both
         *     `ENABLE ALWAYS`), so there is nothing for an as-of to pin (ADR-0019).
         */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One account's posted balance. */
        AccountBalanceRead: {
            /** Format: uuid */
            account_id: string;
            /**
             * @description Always `now`. This endpoint reads the balance CACHE, which means
             *     POSTED (ADR-0010), and pinning it to a cursor would be a second
             *     definition of a balance — so the field is a statement of what the
             *     number means rather than a parameter's echo.
             */
            as_of: string;
            currency: string;
            /**
             * @description Minor units, debit-positive, as an exact-integer decimal string. A
             *     credit-normal account reads negative here and the presentation flip is
             *     the reader's (ADR-0010).
             * @example 442000
             */
            posted_minor: string;
        };
        /**
         * @description The body of `POST /v1/accounts`.
         *
         *     **What is NOT here is the design** (ADR-0021): there is no `category`, no
         *     `normal_balance` and no `counterparty_scope`. `ledger_accounts` carries all
         *     three as COPIES of the chart row, held honest by `fk_accounts__type` and
         *     `fk_accounts__scope` — so a body that stated them could disagree with the
         *     chart, and the caller would be handed a foreign-key error rather than an
         *     answer. The caller names a `purpose` and the server reads the rest, which
         *     makes a whole class of refusals unreachable rather than merely reported.
         */
        AccountBody: {
            /**
             * @description ISO 4217 alphabetic code, three uppercase ASCII letters. One account
             *     holds one currency.
             * @example USD
             */
            currency: string;
            /**
             * @description Caller-supplied replay key, unique per tenant — and in the SAME
             *     namespace a posting's key lives in, because it is the same spine
             *     (`ledger_events`, ADR-0005). Sending the same key with the same body
             *     replays the stored result; with a different body it is refused as
             *     `idempotency_key_reused` (ADR-0013 §2), and that includes a key an
             *     earlier POSTING claimed.
             * @example open-co-1-receivable
             */
            idempotency_key: string;
            /**
             * @description Caller's own JSON object, stored as given. It must BE an object:
             *     `jsonb` would store a bare number as happily, and a metadata field
             *     that is sometimes a scalar is a shape every reader has to defend
             *     against.
             */
            metadata?: unknown;
            /**
             * @description Who owns it. Required for every `owner_type` except `house`, and
             *     refused for `house` — `ck_accounts__house_has_no_owner`, answered as
             *     `account_owner_mismatched`.
             * @example co_1
             */
            owner_id?: string | null;
            owner_type: components["schemas"]["OwnerTypeBody"];
            /**
             * @description The account type, by its chart code — `customer_receivable`,
             *     `fee_revenue`, and whatever else this deployment's chart carries. A
             *     code `account_types` does not hold is `account_type_unknown`.
             * @example customer_receivable
             */
            purpose: string;
            /**
             * Format: int64
             * @description How many stripes the writer spreads this account's balance row across,
             *     1–1024. Omitted means one. **A hint, not an invariant** (ADR-0013 §4):
             *     a reader sums the stripe rows that exist, never the range `0..n-1`, so
             *     nothing is stranded by getting it wrong — but no stripe ever appears
             *     in a response, so this is the only place the number is spoken.
             * @example 64
             */
            stripe_count?: number | null;
            /**
             * @description The book this account belongs to. Named in the body by decision
             *     (ADR-0017): data scoping, never an identity claim.
             * @example t1
             */
            tenant_id: string;
        };
        /**
         * @description The stored result of an accepted opening: the event, and the account it
         *     caused.
         */
        AccountCreated: {
            /**
             * Format: uuid
             * @description The account. Never null, unlike a posting's `transaction_id`: an
             *     accepted opening always wrote one, and a replay finds it by the
             *     natural key its own body names.
             */
            account_id: string;
            /**
             * Format: uuid
             * @description The event row this call claimed — or, on a replay, the one it found.
             *     Opening an account writes an EVENT and no ledger transaction, which is
             *     the case ADR-0005 justified the event log by.
             */
            event_id: string;
        };
        /** @description One page of the account register. */
        AccountListRead: {
            /**
             * @description The page, in creation order — `id` is `uuidv7()`, so ordering by it
             *     orders by when each account was opened.
             *
             *     **An empty list is a legitimate answer** and never a 404: it is what
             *     an unknown tenant, a typo'd tenant, a tenant with no accounts and a
             *     reader scoped elsewhere all produce, and two of those are the
             *     fail-closed path working correctly (ADR-0019).
             */
            accounts: components["schemas"]["AccountRead"][];
            /**
             * Format: uuid
             * @description The `after` to send for the next page, or `null` when this page did
             *     not fill. **A full page means "there may be more", never "there is"**:
             *     the alternative is reading one row past every page to be certain, and
             *     a caller that follows this key to an empty page has learnt the same
             *     thing one request later.
             */
            next_after: string | null;
        };
        /**
         * @description One account, as the register holds it.
         *
         *     **No balance, and that is contract** (ADR-0021): balances are per currency
         *     and per stripe, so a balance per row would be N+1, and
         *     `GET /v1/accounts/{account_id}/balance` answers that question one account
         *     at a time and exactly.
         */
        AccountRead: {
            /** Format: uuid */
            account_id: string;
            /**
             * @description `asset`, `liability`, `equity`, `revenue` or `expense` — the chart's,
             *     copied onto the account and held honest by `fk_accounts__type`.
             */
            category: string;
            /**
             * @description `none`, `shared` or `per_shard` — whether this type's positions may be
             *     summed for reporting, and the reason a `per_shard` type cannot live in
             *     a house account (ADR-0012).
             */
            counterparty_scope: string;
            /**
             * Format: date-time
             * @description When the account was opened — the database's clock.
             */
            created_at: string;
            currency: string;
            /**
             * @description `debit` or `credit`. **Not derivable from `category`**: a loss
             *     allowance is an asset with a credit normal balance, which is why the
             *     schema stores both.
             */
            normal_balance: string;
            /**
             * @description `null` on a house account, which is the ledger's own side and has no
             *     owner.
             */
            owner_id: string | null;
            /** @description `company`, `platform`, `bank_account` or `house`. */
            owner_type: string;
            /** @description The account type, by its chart code. */
            purpose: string;
            /**
             * Format: int32
             * @description How many stripes the writer spreads this account's balance row across.
             *     **The one place a stripe count is spoken** — no stripe VALUE appears
             *     in any response (ADR-0013 §4), and this is the hint, not a position.
             * @example 64
             */
            stripe_count: number;
        };
        /**
         * @description One leg. `amount_minor` is a JSON number here and a decimal STRING on
         *     every report, and the asymmetry is deliberate (ADR-0019): a single posting
         *     is bounded by its column, and only an aggregate can exceed what a JSON
         *     number carries exactly.
         */
        EntryRead: {
            /** Format: uuid */
            account_id: string;
            /**
             * Format: int64
             * @description The account's own gapless sequence number for this leg. The counter is
             *     per `(account, stripe)` — documented, never exposed: no stripe appears
             *     in any response (ADR-0013 §4).
             */
            account_seq: number;
            /**
             * Format: int64
             * @example 2500
             */
            amount_minor: number;
            currency: string;
            /** @description `debit` or `credit`. Direction carries the sign; the amount never does. */
            direction: string;
        };
        /** @description The error body: a stable machine-readable `type`, prose in `detail`. */
        ErrorBody: {
            /** @description Human-readable explanation. Not stable; do not parse. */
            detail: string;
            /**
             * @description Stable machine-readable identifier. Parse this, never `detail`.
             * @example invalid_request
             */
            type: string;
        };
        /**
         * @description Who an account belongs to — the schema's `account_owner_type`. `house` is
         *     the ledger's own side of a movement and is the one value that carries NO
         *     `owner_id`; the other three name one.
         * @enum {string}
         */
        OwnerTypeBody: "company" | "platform" | "bank_account" | "house";
        /**
         * @description One movement of money: `amount_minor` leaves `source` and arrives at
         *     `destination`. Direction is carried by the pair, never by a sign.
         */
        PostingBody: {
            /**
             * Format: int64
             * @description Minor units of `currency`. Strictly positive.
             * @example 2500
             */
            amount_minor: number;
            /**
             * @description ISO 4217 alphabetic code, three uppercase ASCII letters.
             * @example USD
             */
            currency: string;
            /**
             * Format: uuid
             * @description Account the amount arrives at.
             */
            destination: string;
            /**
             * Format: uuid
             * @description Account the amount leaves.
             */
            source: string;
        };
        /** @description One line of a statement face. */
        StatementLineRead: {
            /**
             * @description Minor units, as an exact-integer decimal string — **not a JSON
             *     number**. A report total is an aggregate and can exceed what a JSON
             *     number carries exactly, which would be rounded silently by the parser
             *     at the other end (ADR-0019). It costs every caller one parse,
             *     deliberately.
             * @example 442000
             */
            amount_minor: string;
            caption: string;
            currency: string;
            /** @description The chart's line code. */
            fs_line: string;
            /** @description Which side of the face this line belongs to. */
            side: string;
            /**
             * Format: int32
             * @description The chart's ordering, not a row number.
             */
            sort_order: number;
        };
        /**
         * @description A statement face — the same shape for the balance sheet and the income
         *     statement, because the two functions return the same columns.
         */
        StatementRead: {
            /**
             * Format: int32
             * @description The chart version this face was presented at — always named, never
             *     defaulted. **The residual, stated** (ADR-0019 B6): naming a version
             *     pins the presentation only BELOW `max(version)`, because
             *     `refuse_stale_chart_version()` freezes history and not the present.
             */
            chart_version: number;
            /**
             * @description The face, in the chart's own `sort_order`.
             *
             *     **What is reproducible at a stored cursor, and what is not**
             *     (ADR-0019 B7): the AMOUNTS are; the ROW SET is not. The lines are
             *     enumerated from tables that carry no `xact_id` — one new account with
             *     nothing posted to it added ten balance-sheet rows at a fixed cursor,
             *     every pre-existing amount byte-identical. And an income statement's
             *     amounts carry one carve-out of their own: a period close inserted
             *     AFTER a statement is issued retroactively removes that transaction's
             *     entries from it, because `ledger_period_closes` has no commit position.
             */
            lines: components["schemas"]["StatementLineRead"][];
            /** @example 231000 */
            pinned_cursor: string;
        };
        /**
         * @description Whether the transaction lands on the books or records money that MAY
         *     move. Status never mutates: a pending transaction becomes posted by a NEW
         *     transaction naming it in `resolves_id`, never by an update (ADR-0016).
         * @enum {string}
         */
        StatusBody: "pending" | "posted";
        /** @description The body of `POST /v1/transactions`. */
        TransactionBody: {
            /**
             * Format: date-time
             * @description When the movement is deemed to have happened, RFC 3339. Required —
             *     the writer will not invent a date — EXCEPT on a reversal, where
             *     omission means "the target's own effective_at" (ADR-0016's soft
             *     convention). A supplied date is taken as given, including one below
             *     the target's; the cost of that window is recorded in ADR-0016.
             */
            effective_at?: string | null;
            /**
             * @description Caller-supplied replay key, unique per tenant. Sending the same key
             *     with the same body replays the stored result; with a different body it
             *     is refused as `idempotency_key_reused` (ADR-0013 §2).
             * @example charge-1
             */
            idempotency_key: string;
            /**
             * @description At least one posting — except on a reversal, which must carry NONE:
             *     the server derives the mirror from the target.
             */
            postings?: components["schemas"]["PostingBody"][];
            /**
             * Format: uuid
             * @description The PENDING transaction this one resolves — pending → posted is this
             *     new, posted transaction, never an update to the original (ADR-0016).
             *     The resolution's postings need not mirror the pending amounts (a
             *     partial capture resolves with less); a resolving transaction cannot
             *     itself be pending.
             */
            resolves_id?: string | null;
            /**
             * Format: uuid
             * @description The transaction this one reverses — operational undo, as a NEW
             *     posted transaction (ADR-0016): a posted target is mirrored in full
             *     (same legs, directions flipped, derived by the server — send NO
             *     postings), and a pending target is voided by a zero-posting marker.
             *     The target must be an ordinary posting on this tenant's book,
             *     itself neither a resolution nor a reversal, and not already
             *     superseded.
             */
            reverses_id?: string | null;
            status?: null | components["schemas"]["StatusBody"];
            /**
             * @description The book this transaction belongs to. Named in the body by decision
             *     (ADR-0017): data scoping, never an identity claim — the trust story is
             *     the deployment perimeter's, and authenticating callers is the
             *     deployer's layer.
             * @example t1
             */
            tenant_id: string;
        };
        /**
         * @description The stored result of an accepted operation: the event, and the transaction
         *     it caused.
         */
        TransactionCreated: {
            /**
             * Format: uuid
             * @description The event row this call claimed — or, on a replay, the one it found.
             */
            event_id: string;
            /**
             * Format: uuid
             * @description The transaction the event caused. Nullable by contract: most accepted
             *     operations write no transaction at all (ADR-0013 §2). This endpoint
             *     always writes one, but a replay re-renders whatever was stored.
             */
            transaction_id: string | null;
        };
        /** @description A transaction as the book holds it, with its entries. */
        TransactionRead: {
            /**
             * Format: date-time
             * @description When the movement is deemed to have happened — the caller's clock.
             */
            effective_at: string;
            /**
             * @description The legs. **Empty is a real answer**: a reversal of a pending
             *     transaction is a zero-posting void marker (ADR-0016).
             */
            entries: components["schemas"]["EntryRead"][];
            /**
             * Format: uuid
             * @description The event that caused this transaction.
             */
            event_id: string;
            /** @description `posting` for an ordinary transaction, `period_close` for a close. */
            kind: string;
            /**
             * Format: date-time
             * @description When the row was written — the database's clock. The two axes are
             *     different questions (ADR-0006) and neither is derivable from the other.
             */
            recorded_at: string;
            /**
             * Format: uuid
             * @description The pending transaction this one resolved, if it is a resolution.
             */
            resolves_id: string | null;
            /**
             * Format: uuid
             * @description The transaction this one reversed, if it is a reversal.
             */
            reverses_id: string | null;
            /**
             * @description `pending` or `posted`. **It never mutates**: a pending transaction
             *     becomes posted by a NEW transaction naming it in `resolves_id`
             *     (ADR-0016), so a `pending` here is what was recorded and not a stage
             *     this row is passing through.
             */
            status: string;
            /** Format: uuid */
            transaction_id: string;
        };
        /** @description The trial balance, and the cursor it was pinned at. */
        TrialBalanceRead: {
            /**
             * @description The commit position this report ran at — supplied or server-pinned.
             *     Store it to re-run this exact report; a decimal string, because an
             *     `xid8` is a 64-bit unsigned value and JSON numbers are not.
             * @example 231000
             */
            pinned_cursor: string;
            /**
             * @description One row per `(account, currency)` with any activity in the window.
             *     **An empty list is a legitimate answer** and never a 404: it is what
             *     an unknown tenant, a typo'd tenant, a tenant with no accounts, a
             *     reader scoped elsewhere and an unscoped session all produce, and two
             *     of those five are the fail-closed path working correctly (ADR-0019).
             */
            rows: components["schemas"]["TrialBalanceRowRead"][];
        };
        /**
         * @description One `(account, currency)` of the trial balance. Every amount is a decimal
         *     string.
         */
        TrialBalanceRowRead: {
            /** Format: uuid */
            account_id: string;
            /**
             * @description The ARITHMETIC value — roll up with this one. `normal_balance` never
             *     enters it, so a contra account carries its own sign instead of being
             *     flipped twice.
             * @example 442000
             */
            balance_debit_positive: string;
            /** @description `asset`, `liability`, `equity`, `revenue` or `expense`. */
            category: string;
            /**
             * @description Gross credits in the window.
             * @example 0
             */
            credits: string;
            currency: string;
            /**
             * @description Gross debits in the window.
             * @example 442000
             */
            debits: string;
            /** @description The account type — the chart's code, e.g. `operating_cash`. */
            purpose: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAccounts: {
        parameters: {
            query: {
                /**
                 * @description The book to read.
                 * @example t1
                 */
                tenant_id: string;
                /**
                 * @description How many accounts at most, 1–1000. Omitted means 100. A value outside
                 *     the window is REFUSED rather than clamped: a clamped page is an answer
                 *     to a question the caller did not ask, and nothing on the wire would
                 *     say so.
                 * @example 100
                 */
                limit?: number;
                /**
                 * @description The last `account_id` of the previous page — send back the
                 *     `next_after` an earlier page answered with. Keyset, never an offset
                 *     (ADR-0021): an offset shifts under concurrent inserts, so a caller
                 *     paging a growing book silently skips rows.
                 */
                after?: string;
                /**
                 * @description Equality on the chart code. **Equality, not search**: no pattern
                 *     matching and no free text.
                 * @example customer_receivable
                 */
                purpose?: string;
                /**
                 * @description Equality on the owner. It selects no house accounts, which have no
                 *     owner at all.
                 * @example co_1
                 */
                owner_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the account register, in creation order. An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type — including an `after` that is not a UUID. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is one of: `invalid_request` (a `limit` outside 1–1000, zero or negative included — refused rather than clamped) or `tenant_mismatch`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read failed. `type` is `internal`. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    openAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountBody"];
            };
        };
        responses: {
            /** @description Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2). */
            200: {
                headers: {
                    /** @description `true`: this response re-renders a previously stored result. */
                    "Idempotency-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountCreated"];
                };
            };
            /** @description Opened: this call claimed the idempotency key and wrote the account and its event atomically. */
            201: {
                headers: {
                    /** @description `false`: this response is the first for its idempotency key. */
                    "Idempotency-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountCreated"];
                };
            };
            /** @description The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request body exceeds the size limit. `type` is `invalid_request`. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request's `Content-Type` is not `application/json`. `type` is `invalid_request`. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused, and nothing was written. Every `type` below is a constraint the schema already holds, refused by name rather than surfaced as a database error (ADR-0021). `type` is one of: `invalid_request` (a precondition on the body failed — a `stripe_count` outside 1–1024, a currency that is not three uppercase letters, a blank tenant, metadata that is not an object — or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key, or resend the original request unchanged; the key namespace is shared with `POST /v1/transactions`, deliberately, because it is the same spine), `account_type_unknown` (`purpose` names no row in this deployment's chart), `account_exists` (`uq_accounts__owned` or `uq_accounts__house` already holds this account; the refusal does not say whose, because within one tenant a collision is always the caller's own), `account_owner_mismatched` (`ck_accounts__house_has_no_owner` — a house account has no owner and an owned account must have one), `account_type_requires_an_owner` (`ck_accounts__per_shard_is_owned` — a type whose split key IS the counterparty cannot be held in a house account, because such an account nets every counterparty at write time and no report can recover it). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getAccountBalance: {
        parameters: {
            query: {
                /**
                 * @description The book to read.
                 * @example t1
                 */
                tenant_id: string;
                /**
                 * @description ISO 4217 alphabetic code.
                 * @example USD
                 */
                currency: string;
            };
            header?: never;
            path: {
                /** @description The account to read. */
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The posted balance, summed over the account's balance rows. An account that exists and has never been written answers `"0"` — which is why this endpoint reads the account register and not only the balance cache (ADR-0019). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type — including an `account_id` path segment that is not a UUID. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such account on this book, or the account does not hold that currency. `type` is `account_unknown` — note that the write path returns 422 under this same `type`, deliberately: there the caller must change the request, here the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is `tenant_mismatch`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read failed. `type` is `internal`. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getBalanceSheet: {
        parameters: {
            query: {
                /** @example t1 */
                tenant_id: string;
                /**
                 * @description The instant to report the position as at, RFC 3339. **This is a
                 *     period's `ends_at`, never a business date**: the predicate is
                 *     `effective_at < as_of`, so a business date returns the position at the
                 *     START of that day and silently loses a day at every period boundary
                 *     (ADR-0019). Nothing raises, and the number is plausible.
                 * @example 2026-02-01T00:00:00Z
                 */
                as_of: string;
                /** @example 231000 */
                cursor?: string;
                /**
                 * @description The chart version to present at. Omitted means the version the book is
                 *     on now, resolved by the read path and reported back in
                 *     `chart_version` — never left to the SQL default, which resolves at run
                 *     time (ADR-0019 B6).
                 * @example 1
                 */
                chart_version?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The face, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is one of: `invalid_request` (an `as_of` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown` (no such version, or no chart has been seeded at all), `chart_version_incomplete` (the version does not present every account type with posted entries as at this instant — refused rather than silently dropping a sub-book from a face that would still balance), or `tenant_mismatch`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report failed. `type` is `internal`. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getIncomeStatement: {
        parameters: {
            query: {
                /** @example t1 */
                tenant_id: string;
                /**
                 * @description Inclusive lower bound on `effective_at`, RFC 3339.
                 * @example 2026-01-01T00:00:00Z
                 */
                effective_from: string;
                /**
                 * @description EXCLUSIVE upper bound on `effective_at`, RFC 3339.
                 * @example 2026-02-01T00:00:00Z
                 */
                effective_to: string;
                /** @example 231000 */
                cursor?: string;
                /** @example 1 */
                chart_version?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The statement, the chart version it was presented at, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404 (ADR-0019). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8`), `cursor_invalid` (a legal `xid8` outside the plausible range), `chart_version_unknown`, `chart_version_incomplete` (the version does not present every account type with posted entries in this window), or `tenant_mismatch`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report failed. `type` is `internal`. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getTrialBalance: {
        parameters: {
            query: {
                /** @example t1 */
                tenant_id: string;
                /**
                 * @description Inclusive lower bound on `effective_at`, RFC 3339.
                 * @example 2026-01-01T00:00:00Z
                 */
                effective_from: string;
                /**
                 * @description EXCLUSIVE upper bound on `effective_at`, RFC 3339 — the range is
                 *     half-open, as it is on all three report functions (ADR-0011 §A3).
                 * @example 2026-02-01T00:00:00Z
                 */
                effective_to: string;
                /**
                 * @description The commit position to pin the report to — a `pinned_cursor` from an
                 *     earlier report. Omit it and one is pinned server-side and returned.
                 * @example 231000
                 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trial balance, and the cursor it was pinned at. An unknown tenant answers 200 with an empty list, never 404: there is no tenant registry to consult, so inventing the status would mean inventing the registry (ADR-0019). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalanceRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is one of: `invalid_request` (an `effective_from` or `effective_to` that is not an RFC 3339 instant, or a `cursor` that is not an `xid8` at all), `cursor_invalid` (a syntactically valid `xid8` that is above this cluster's horizon or at or below the book's oldest entry — `-1` wraps to the maximum and would return the entire UNPINNED book, `0` would return an all-zero balanced fabrication, and the database cannot refuse either), or `tenant_mismatch`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report failed. `type` is `internal`. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The report exceeded this deployment's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionBody"];
            };
        };
        responses: {
            /** @description Replayed: this key was already accepted with this same body. The stored result is re-rendered — never a cached response body — and nothing was written (ADR-0013 §2). */
            200: {
                headers: {
                    /** @description `true`: this response re-renders a previously stored result. */
                    "Idempotency-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionCreated"];
                };
            };
            /** @description Posted: this call claimed the idempotency key and wrote the transaction atomically. */
            201: {
                headers: {
                    /** @description `false`: this response is the first for its idempotency key. */
                    "Idempotency-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionCreated"];
                };
            };
            /** @description The request body is not syntactically valid JSON. `type` is `invalid_request`; `detail` carries the parser's message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request body exceeds the size limit. `type` is `invalid_request`. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request's `Content-Type` is not `application/json`. `type` is `invalid_request`. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused, and nothing was written. The caller must CHANGE the request to escape — which is why this is 422, not 400 or 409 (ADR-0013 §2). `type` is one of: `invalid_request` (a precondition on the body failed, or a field failed to deserialize into its documented type), `idempotency_key_reused` (same key, different body — send a new key or resend the original request unchanged), `account_unknown` (a posting names an account that does not exist or does not hold that currency), `resolve_target_unknown` (`resolves_id` names no transaction on this tenant's book), `resolve_target_not_pending` (only a pending transaction can be resolved — its status never mutates), `reverse_target_unknown` (`reverses_id` names no transaction on this tenant's book), `reverse_target_not_reversible` (only an ordinary posting that is itself neither a resolution nor a reversal can be reversed), `target_already_superseded` (the named target already has its one supersession — resolved or reversed, either fate is final). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The write failed; nothing was committed. `type` is `internal`, and the caller gets no internals — the operator's log has the error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query: {
                /**
                 * @description The book to read.
                 * @example t1
                 */
                tenant_id: string;
            };
            header?: never;
            path: {
                /** @description The transaction to read. */
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction and its entries. `entries` is empty for a void — the zero-posting marker a reversal of a PENDING transaction writes (ADR-0016). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description A required query parameter is missing, or a value would not deserialize into its documented type — including a `transaction_id` path segment that is not a UUID. `type` is `invalid_request`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such transaction on this tenant's book. `type` is `transaction_unknown`. Note that an unknown TENANT is not 404 but 200-with-nothing on the report routes, and 404 here: there is no tenant registry to consult, so a wrong `tenant_id` is indistinguishable from a book that does not hold this transaction. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Refused. `type` is `tenant_mismatch` — the `tenant_id` asked about is not the scope the read path set on the session. Vacuous today by construction and declared anyway (ADR-0019). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read failed. `type` is `internal`, and the caller gets no internals — the operator's log has the error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The read exceeded the read pool's `statement_timeout` (`57014`). `type` is `report_timed_out`. **503, not 500 and not 504**: the service is healthy, the request was too expensive, and retrying it unchanged fails identically (ADR-0019). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
